- web/components/templates/dashboard/metricsPanel.tsx
- web/components/templates/dashboard/requestTable.tsx
> Model in table and update total cost to use finetune pricing

- web/components/shared/layout/authLayout.tsx
- web/components/shared/notification/Notification.tsx
- web/components/shared/notification/NotificationContext.tsx
- web/components/shared/notification/useNotification.tsx
- web/components/templates/billing/billingPage.tsx
- web/components/templates/dashboard/dashboardPage.tsx
- web/components/templates/keys/keyPage.tsx
- web/components/templates/models/modelPage.tsx
- web/components/templates/requests/requestsPage.tsx
- web/components/templates/users/usersPage.tsx
- web/lib/useKeys.ts
- web/pages/_app.tsx
- web/pages/keys.tsx
- web/pages/requests.tsx
- web/pages/usage.tsx
- web/pages/users.tsx
- web/services/lib/keys.ts
- Alert user is no key added
- flicker on AuthLayout fixed (passed user from serverSideProps)
- autoFocus on view modal removed
- notifications added (add key)
-
> feat: ui improvements

- web/components/templates/usage/usagePage.tsx
> fix "free free" usage typo

- web/components/templates/requests/requestsPage.tsx
> no more request quote - Only showing if there is an array that is a resonse request

- web/supabase/config.toml
- web/supabase/migrations/20221201092605_response_request_view.sql
- web/supabase/migrations/20221203225026_metrics.sql
- web/supabase/migrations/20221214040640_user_view.sql
ADD compatibility to Supabase PostgreSQL 15
https://github.com/supabase/supabase/discussions/1501#discussioncomment-715670
> ADD Compatibilty to Postgresql 15 on migrations

- web/components/shared/themed/themedAdvancedFilters.tsx
- web/components/shared/themed/themedDropdown.tsx
- web/components/shared/themed/themedTableHeader.tsx
- web/components/templates/requests/requestsPage.tsx
- web/pages/api/export/requests/index.ts
- change limit to 10k
- test 5k
- test 100
- test limit
- test 5k
- test 10k
- okay, back to 5k
- fix filter ui
> fix: filter ui

- web/README.md
Script names parts are transposed, this fixes that.
> fix: correct script name

- web/components/templates/requests/requestsPage.tsx
- web/components/templates/requests/useRequestsPage.tsx
> Revert "fixed columns from jumping"

- worker/e2e_test.py
- worker/src/index.ts
added full pass through where if logging to SB fails, pass through still works
> Remove worker reliance on SB

- web/components/templates/dashboard/dashboardPage.tsx
- web/lib/api/metrics/getModelUsageOverTime.ts
- web/lib/api/metrics/getRequestCount.ts
- web/lib/api/metrics/getXRequestDate.ts
- web/lib/api/metrics/modelMetrics.ts
- web/lib/api/metrics/timeMetrics.ts
- web/lib/api/request/request.ts
- web/services/lib/filters/filterDefs.ts
- web/services/lib/filters/filters.ts
> Revert "optimize queries a bit"

- web/components/templates/dashboard/dashboardPage.tsx
- web/lib/api/metrics/getModelUsageOverTime.ts
- web/lib/api/metrics/getRequestCount.ts
- web/lib/api/metrics/getXRequestDate.ts
- web/lib/api/metrics/modelMetrics.ts
- web/lib/api/metrics/timeMetrics.ts
- web/lib/api/request/request.ts
- web/pages/api/prompt_values/params.ts
- web/services/lib/filters/filterDefs.ts
- web/services/lib/filters/filters.ts
> Revert "Revert "optimize queries a bit""

- web/components/templates/requests/useRequestsPage.tsx
updated model to fall back to response model if request model is not there
> Fixed models in request Table

- web/components/shared/themed/themedAdvancedFilters.tsx
- web/components/shared/themed/themedTableHeader.tsx
- web/components/shared/themed/themedTextDropDown.tsx
- web/components/templates/requests/requestsPage.tsx
- web/components/templates/requests/useRequestsPage.tsx
- web/lib/api/properties/propertyParams.ts
- web/lib/result.ts
- web/pages/api/properties/params.ts
- web/services/lib/filters/filterDefs.ts
- web/services/lib/filters/filters.ts
- web/services/lib/propertyParams.ts
> Revert "Added search on filters"

- web/components/templates/usage/usagePage.tsx
- fix usage bar
- ff: estimated cost fix
> feat: usage bar

- web/components/shared/auth/login.tsx
- web/components/templates/usage/usagePage.tsx
- web/pages/api/stripe/create_subscription/index.ts
- web/pages/api/user_settings/index.ts
- fix usage bar
- ff: estimated cost fix
- fix stripe
> feat: stripe fix

- web/components/templates/usage/usagePage.tsx
- web/services/hooks/userSettings.tsx
- fix
- quick usage page patch
> bugfix: usage page

- web/graphql.schema.json
- web/lib/api/graphql/query/heliconeRequest.ts
- web/lib/api/graphql/schema/main.graphql
- web/lib/api/graphql/schema/types/graphql.tsx
- web/lib/api/request/request.ts
- worker/src/lib/dbLogger/logResponse.ts
added filtering by user and created at. also changed worker to trunc user_id so that we can add an index on that column
> GraphQL filters and fixes

- docker/dockerfiles/dockerfile_worker
Context: https://github.com/cloudflare/workers-sdk/issues/2583
> Install libc++ related deps in worker

- web/components/templates/requestsV2/builder/ChatGPTBuilder.tsx
- web/components/templates/requestsV2/builder/GPT3Builder.tsx
- web/components/templates/requestsV2/builder/abstractRequestBuilder.tsx
- web/components/templates/requestsV2/builder/functionGPTBuilder.tsx
- web/components/templates/requestsV2/initialColumns.tsx
- web/components/templates/requestsV2/requestDrawerV2.tsx
- web/components/templates/requestsV2/statusBadge.tsx
Edge case where status is success 
But there is an error
> Add status type

- web/components/templates/requestsV2/builder/functionGPTBuilder.tsx
- web/components/templates/requestsV2/requestDrawerV2.tsx
- function fix
- function fix and drawer state fix
> function-fix

- web/components/templates/organizations/orgsPage.tsx
- web/components/templates/usage/renderOrgItem.tsx
- web/components/templates/welcome/steps/eventListen.tsx
- web/components/templates/welcome/welcomePage.tsx
- web/pages/api/request/ch/count.ts
- web/pages/dashboard.tsx
- web/pages/index.tsx
- web/pages/usage.tsx
- web/pages/welcome.tsx
- web/services/hooks/dashboard.tsx
- move welcome redirect
- test with 10
> dashboard-gate

- web/components/templates/dashboard/dashboardPage.tsx
- web/pages/api/organization/tier.ts
- web/pages/dashboard.tsx
- web/pages/dashboard_v2.tsx
- web/pages/demo.tsx
- web/services/hooks/dashboard.tsx
- fix org change bug
- added org tier checking
> dashboard-gate-fix

- web/components/templates/welcome/welcomePage.tsx
- web/pages/index.tsx
- add skip onboarding
- onboarding fix
- check user setting on home page
> onboarding-fix

- mitmproxy.sh
> Enable caching in mitm

- mitmproxy.sh
> Add custom properties

- web/components/shared/layout/authLayout.tsx
- web/components/shared/layout/orgDropdown.tsx
- web/components/templates/usage/usagePage.tsx
- org dropdown update
- org dropdown update
> org-dropdown

- web/lib/api/graphql/helpers/auth.ts
- web/lib/supabaseServer.ts
- web/lib/wrappers/supabase.ts
- web/pages/api/organization/[id]/add_member.ts
- web/pages/api/organization/[id]/remove_member.ts
- web/pages/api/organization/tier.ts
- web/pages/api/stripe/event_webhook/index.ts
- web/pages/api/user_settings/index.ts
- web/services/lib/filters/filters.ts
This reverts commit ccf0db8495f22aee7693bcbf4595d9dc03a85932.
> Revert "Supabase url notstatic (#576)"

- web/components/templates/welcome/diffHighlight.tsx
- web/components/templates/welcome/steps/codeIntegration.tsx
- web/components/templates/welcome/steps/codeSnippets/anthropic-proxy.tsx
- web/components/templates/welcome/steps/codeSnippets/openai-async.tsx
- web/components/templates/welcome/steps/methodFork.tsx
- web/components/templates/welcome/welcomePage.tsx
- web/styles/index.css
- proxy v async
- onboarding forked
> onboarding-fork

- web/components/shared/notification/Notification.tsx
- web/components/shared/notification/NotificationContext.tsx
- web/components/shared/themed/table/themedTableHeader.tsx
- web/components/shared/themed/table/themedTableV5.tsx
- web/components/shared/themed/themedTableHeader.tsx
- web/components/shared/themed/themedToggle.tsx
- web/components/templates/requests/requestsPage.tsx
- web/components/templates/requestsV2/requestsPageV2.tsx
- web/components/templates/requestsV2/useRequestsPageV2.tsx
- web/services/hooks/requests.tsx
> added live updating on request page

- web/components/shared/layout/authLayout.tsx
- web/components/shared/themed/themedDrawer.tsx
- web/components/shared/themed/themedTable.tsx
- web/components/templates/dashboard/dashboardPage.tsx
- web/components/templates/requestsV2/modelPill.tsx
- web/components/templates/webhooks/addWebhookForm.tsx
- web/components/templates/webhooks/webhooksPage.tsx
- web/pages/api/metrics/latencyOverTime.ts
- web/pages/api/webhooks/add.ts
- web/services/hooks/featureFlags.tsx
- auth layout check for webhooks
- webhooks rewrite
> webhook-rework

- web/components/shared/metrics/metricsPanel.tsx
- web/components/templates/dashboard/dashboardPage.tsx
- web/components/templates/users/usersPageV2.tsx
- web/services/hooks/users.tsx
- remove dau from users page
- graph cleanup
> graph-cleanup

- docs/getting-started/integration-method/anthropic.mdx
Thanks to Raunak Chowdhuri
https://twitter.com/helicone_ai/status/1686840508658876419
> Fixed anthropic.mdx

- docs/getting-started/integration-method/litellm.mdx
- docs/mint.json
Adding the tutorial for using Helicone with LiteLLM
> add litellm to helicone docs

- web/components/templates/requests/chat.tsx
- web/components/templates/requestsV2/RequestView.tsx
- web/components/templates/requestsV2/requestDrawerV2.tsx
- web/components/templates/requestsV2/requestsPageV2.tsx
> added request collapse view

- docker/docker-compose.yml
- worker/package.json
- worker/src/index.ts
- worker/src/lib/HeliconeProxyRequest/forwarder.ts
- worker/src/lib/db/postgres.ts
- worker/src/lib/dbLogger/DBLoggable.ts
- worker/src/lib/dbLogger/logResponse.ts
- worker/src/routers/apiRouter.ts
The supabase js client does unnecessary SQL logic as well as not using pgbouncer. This should hopefully increase the insertion speed for the request records
> Request insert improvement

- web/components/templates/pricing/premSupport.tsx
- web/components/templates/pricing/pricingPage.tsx
> added priority support pricing

- web/components/shared/layout/authLayout.tsx
- web/components/templates/playground/chatPlayground.tsx
- web/components/templates/playground/chatRow.tsx
- web/components/templates/requests/chat.tsx
- web/components/templates/requests/useRequestsPage.tsx
- web/components/templates/requestsV2/builder/chatGPTBuilder.tsx
- web/components/templates/requestsV2/builder/requestBuilder.tsx
- web/components/templates/requestsV2/modelPill.tsx
- web/components/templates/requestsV2/requestsPageV2.tsx
- worker/.gitignore
- remove banner
- yarn-lock ignore
- function ui
> functions-ui

- web/components/shared/layout/authLayout.tsx
- web/components/templates/requestsV2/builder/chatGPTBuilder.tsx
- worker/.gitignore
- remove banner
- yarn-lock ignore
> remove-banner

- web/components/shared/layout/authLayout.tsx
- web/components/shared/layout/orgDropdown.tsx
- web/components/templates/usage/usagePage.tsx
- web/pages/usage.tsx
- web/services/hooks/userSettings.tsx
> usage page update

- web/components/templates/dashboard/dashboardPage.tsx
> dashboard-feedback

- docs/introduction.mdx
> ✨ Add href's to introduction page cards

- web/components/shared/authHeader.tsx
- web/components/shared/layout/authLayout.tsx
- web/components/templates/jobs/jobsPage.tsx
- web/components/templates/jobs/single/JobNode.tsx
- web/components/templates/jobs/single/flow.tsx
- web/components/templates/jobs/single/nodeDirectory.tsx
- web/components/templates/jobs/single/nodeOutline.tsx
- web/components/templates/jobs/single/singleJobPage.tsx
- web/components/templates/jobs/useJobPage.tsx
- web/components/templates/requestsV2/requestDrawerV2.tsx
- web/pages/jobs/index.tsx
> cluster rework

- web/components/templates/jobs/jobsPage.tsx
- web/components/templates/jobs/statusBadge.tsx
- web/lib/sql/jobs.ts
- web/pages/api/graphql/index.ts
- clean up status on job page
- new timeout state
> pending job status

- web/components/shared/themed/themedDropdown.tsx
- web/components/templates/playground/chatPlayground.tsx
- web/components/templates/playground/chatRow.tsx
- web/components/templates/playground/playgroundPage.tsx
- web/components/templates/playground/resizeTextArea.tsx
- web/components/templates/requests/chat.tsx
- web/pages/api/open_ai/chat/index.ts
- web/services/hooks/playground.tsx
- web/services/lib/openAI.ts
> playground-v2

- web/package.json
- web/yarn.lock
- worker/package-lock.json
- worker/package.json
> Update project-rosetta dependency to version

- web/components/templates/dashboard/dashboardPage.tsx
- web/components/templates/dashboard/styledAreaChart.tsx
- web/components/templates/playground/chatPlayground.tsx
- web/components/templates/playground/playgroundPage.tsx
- web/components/templates/requests/completion.tsx
- web/components/templates/requestsV2/builder/GPT3Builder.tsx
- web/components/templates/requestsV2/builder/claudeBuilder.tsx
- web/components/templates/requestsV2/builder/customBuilder.tsx
- web/components/templates/requestsV2/builder/embeddingBuilder.tsx
- web/components/templates/requestsV2/builder/moderationBuilder.tsx
- web/components/templates/requestsV2/builder/unknownBuilder.tsx
- web/pages/api/open_ai/chat/index.ts
- web/services/lib/openAI.ts
- json view for completions
- views from the six
- models on dash
> deprecate-models

- web/lib/api/request/request.ts
> Fix truncation issue in getRequests and

- web/services/lib/filters/filterDefs.ts
- web/services/lib/filters/filters.ts
> Fix user page filtering

- helicone-node/package-lock.json
- helicone-node/package.json
- helicone-node/tests/UsageExample.ts
> Update dependencies in package.json and

- web/components/shared/themed/table/requestRow.tsx
- web/components/templates/playground/chatPlayground.tsx
- web/components/templates/playground/chatRow.tsx
- web/components/templates/requests/chat.tsx
- web/components/templates/requests/useRequestsPage.tsx
- web/components/templates/requestsV2/builder/chatBuilder.tsx
- web/components/templates/requestsV2/builder/chatGPTBuilder.tsx
- web/components/templates/requestsV2/builder/requestBuilder.tsx
- web/components/templates/requestsV2/modelPill.tsx
- image support
- image support
> image support

- worker/src/lib/HeliconeProxyRequest/mapper.ts
Docs: https://developers.cloudflare.com/ai-gateway/
Closes https://github.com/Helicone/helicone/issues/1030
> permit Cloudflare AI gateway as AI base

- web/components/templates/requests/completion.tsx
- web/components/templates/requestsV2/builder/unknownBuilder.tsx
- unknown model tooltip
- pending mapping
> unknown-mapping

- web/components/templates/playground/chatPlayground.tsx
- web/components/templates/playground/chatRow.tsx
- web/components/templates/requests/chat.tsx
- css for render
- playground-css
- add latency to playground
- latency
> latency playground

- web/components/shared/layout/authLayout.tsx
- web/components/templates/organization/plan/orgPlanPage.tsx
- web/components/templates/organization/plan/renderOrgPlan.tsx
- web/components/templates/requests/chat.tsx
- web/components/templates/requests/completion.tsx
- web/components/templates/requestsV2/tableFooter.tsx
- web/components/templates/users/userModal.tsx
- web/components/templates/users/usersPageV2.tsx
- web/components/templates/webhooks/addWebhookForm.tsx
- web/pages/organization/plan.tsx
- web/services/hooks/users.tsx
- better css for render
- format numbers
- user count on users page
> user-count

- docs/getting-started/integration-method/gateway-fallbacks.mdx
- docs/mint.json
- worker/src/helpers.ts
- worker/src/lib/HeliconeHeaders.ts
- worker/src/lib/HeliconeProxyRequest/mapper.ts
- worker/src/lib/RequestWrapper.ts
- worker/src/routers/gatewayRouter.ts
```python
url = "http://gateway_staging.hconeai.com/v1/chat/completions"
headers = {
"Content-Type": "application/json",
"Helicone-Auth": "Bearer <Helicone KEY>",
"Helicone-Fallbacks": json.dumps([
{
"target-url": "https://api.openai.com",
"headers": {
"Authorization": "Bearer <OpenAI Key>",
},
"onCodes": [{"from": 400, "to": 500}]
},
{
"target-url": "https://api.lemonfox.ai",
"headers": {
"Authorization": "Bearer <LemonFox Key>",
"Content-Type": "application/json",
},
"onCodes": [401, 403],
"bodyKeyOverride": {
"model": "zephyr-chat",
}
},
]),
}
payload = {
"model": "gpt-4",
"messages": [
{
"role": "user",
"content": "What is the meaning of life?"
}
],
"max_tokens": 300
}
response = requests.post(url, headers=headers, data=json.dumps(payload))
print("Fallback index used: ", …
```
> Worker fallback

- web/components/templates/home/globe.tsx
- web/components/templates/pricing/pricingPage.tsx
- slower globe
- pricing update
> pricing-update

- docs/features/advanced-usage/caching.mdx
- docs/features/advanced-usage/vault.mdx
Vault to Key Vault in vault.mdx
> Update cache parameters in caching.mdx and rename

- web/components/templates/welcome/steps/createOrg.tsx
- web/components/templates/welcome/welcomePage.tsx
- onboarding local storage
- add next and prev to onboarding flow
> onboarding-update

- web/components/shared/metrics/metricsPanel.tsx
- web/components/templates/dashboard/dashboardPage.tsx
- web/components/templates/dashboard/useDashboardPage.tsx
- web/components/templates/properties/propertyCard.tsx
- web/components/templates/requests/completion.tsx
- web/components/templates/requestsV2/requestsPageV2.tsx
- web/components/templates/users/initialColumns.tsx
- web/components/templates/users/userModal.tsx
- web/components/templates/users/usersPageV2.tsx
- web/lib/api/db/dbExecute.ts
- web/lib/api/metrics/getRequestOverTime.ts
- web/lib/api/metrics/getXOverTime.ts
- web/pages/api/metrics/requestStatusOverTime.ts
- web/pages/requests.tsx
- first active in users page
- completion text size
- user modal redirects to request page with filters
- default size 25
- properties redirect to requests page
- requests over time with status codes
- model click maintains url
- clean up
> unified-dashboard

- web/components/templates/alerts/createAlertModal.tsx
- web/tailwind.config.js
- alert emails
- tailwind config
> alert-email

- web/components/shared/layout/authLayout.tsx
- web/components/shared/layout/organizationContext.tsx
- web/lib/api/handlerWrappers.ts
- web/pages/api/organization/[id]/members.ts
- web/pages/index.tsx
- web/services/hooks/organizations.tsx
Reverts Helicone/helicone#1230
> Revert "Customer portal changes 3"

- web/components/shared/loadingAnimation.tsx
- web/components/templates/welcome/welcomePage.tsx
- add skip onboarding button
- remove xmas
> skip-button

- web/components/templates/users/userModal.tsx
> quick filter error fix by checking type in UI

- web/components/shared/layout/authLayout.tsx
- web/components/templates/enterprise/portal/customerRow.tsx
- web/components/templates/enterprise/portal/id/portalIdPage.tsx
- web/components/templates/enterprise/portal/id/providerKeyList.tsx
- web/components/templates/enterprise/portal/portalPage.tsx
- web/components/templates/organization/createOrgForm.tsx
- web/components/templates/organization/members/orgMembersPage.tsx
- web/pages/enterprise/portal/[id]/index.tsx
- web/services/hooks/organizations.tsx
- portal enterprise
- dark mode and lint
> portal-member-id

- web/pages/signin.tsx
Reverts Helicone/helicone#1331
> Revert "redirect signin to dashboard"

- web/components/layout/authLayout.tsx
- web/components/templates/cache/cachePage.tsx
- web/components/templates/dashboard/dashboardPage.tsx
- web/components/templates/home/codeSnippet.tsx
- web/components/templates/organization/addMemberModal.tsx
- web/components/templates/users/initialColumns.tsx
- web/services/hooks/dashboard.tsx
- base url langchain js fix
- user page cost 6 decs
- seat-size
- dashboard restrictions
- restrict cache
> small-nits

- web/components/shared/themed/table/requestRow.tsx
- web/components/shared/themed/table/requestRowView.tsx
- web/components/shared/themed/table/themedTableHeader.tsx
- web/components/shared/themed/themedTimeFilter.tsx
- web/components/templates/requests/chat.tsx
- web/components/templates/requestsV2/builder/GPT3Builder.tsx
- web/components/templates/requestsV2/builder/abstractRequestBuilder.tsx
- web/components/templates/requestsV2/builder/chatBuilder.tsx
- web/components/templates/requestsV2/builder/chatGPTBuilder.tsx
- web/components/templates/requestsV2/builder/claudeBuilder.tsx
- web/components/templates/requestsV2/builder/completionBuilder.tsx
- web/components/templates/requestsV2/builder/customBuilder.tsx
- web/components/templates/requestsV2/builder/dalleBuilder.tsx
- web/components/templates/requestsV2/builder/embeddingBuilder.tsx
- web/components/templates/requestsV2/builder/moderationBuilder.tsx
- web/components/templates/requestsV2/builder/unknownBuilder.tsx
- web/components/templates/requestsV2/requestCard.tsx
- web/components/templates/requestsV2/requestRow.tsx
- table header ui
- row-view-v2
> row-view-v2

- web/lib/api/metrics/costCalc.ts
- web/lib/sql/constants.ts
- worker/src/lib/limits/check.ts
Model name in response is changed:
text-embedding-ada-002-v2 -> text-embedding-ada-002
> Openai model name update text-embedding-ada-002-v2 -> text-embedding-ada-002

- web/components/shared/authHeader.tsx
- web/components/shared/themed/table/themedTableHeader.tsx
- web/components/shared/themed/table/themedTableV5.tsx
- web/components/templates/cache/cachePage.tsx
- web/components/templates/developer/developerPage.tsx
- web/components/templates/jobs/jobsPage.tsx
- web/components/templates/properties/propertiesPage.tsx
- web/components/templates/requestsV2/requestsPageV2.tsx
- web/components/templates/settings/settingsPage.tsx
- web/components/templates/users/id/userIdPage.tsx
- web/components/templates/users/usersPageV2.tsx
- web/pages/users/[id].tsx
- web/pages/users/index.tsx
- web/services/hooks/users.tsx
> user-id-page

- worker/package.json
OMFG - The packages were not in dev ... wtf
> moved packages to dev

- CONTRIBUTING_GUIDELINES.md
- web/lib/sql/constants.ts
- worker/src/lib/limits/check.ts
> added price fixes

- clickhouse/migrations/schema_22_target_url.sql
- worker/src/lib/db/clickhouse.ts
- worker/src/lib/dbLogger/clickhouseLog.ts
Added target_url to clickhouse
> Added target_url to clickhouse

- worker/src/lib/dbLogger/insertQueue.ts
error if request insert failed
> Handle Request Id duplication error

- web/components/templates/requestsV2/builder/chatGPTBuilder.tsx
- **response text**
- **rm hello**
- **error messages**
> req-parsing

- .github/workflows/tests.yml
- clickhouse/migrations/schema_23_request_ip.sql
- supabase/migrations/20240314111745_request_ip.sql
- valhalla/jawn/src/lib/db/database.types.ts
- web/supabase/database.types.ts
- worker/src/lib/HeliconeProxyRequest/forwarder.ts
- worker/src/lib/db/clickhouse.ts
- worker/src/lib/dbLogger/DBLoggable.ts
- worker/src/lib/dbLogger/clickhouseLog.ts
- worker/src/lib/dbLogger/logResponse.ts
- worker/supabase/database.types.ts
> Storing request IP

- web/components/shared/themed/themedAdvancedFilters.tsx
- web/components/templates/users/initialColumns.tsx
Fixed timezones in Users page filters
> Fixed timezones in Users page filters

- web/components/shared/themed/themedDrawer.tsx
- web/components/shared/themed/themedModal.tsx
- web/components/templates/requestsV2/costPill.tsx
- web/components/templates/requestsV2/initialColumns.tsx
Flag models we cannot calculate cost
> Flag models we cannot calculate cost

- web/components/shared/themed/table/requestRow.tsx
- web/components/templates/requestsV2/requestCard.tsx
> Row and Card flag models

- web/components/shared/themed/table/requestRow.tsx
- web/components/templates/dashboard/dashboardPage.tsx
- web/components/templates/dashboard/quantilesGraph.tsx
- web/components/templates/requestsV2/initialColumns.tsx
- web/components/templates/requestsV2/requestCard.tsx
- web/pages/api/metrics/quantiles.ts
- web/services/hooks/quantiles.tsx
Quantiles filter + Cost Unsupported fixes
> Quantiles filter + Cost Unsupported fixes

- worker/src/lib/dbLogger/DBLoggable.ts
- worker/src/lib/dbLogger/parsers/anthropicStreamParser.ts
Reverts Helicone/helicone#1570
> Revert "fixed issue for non-streamed claude requests"

- web/components/shared/themed/themedModal.tsx
- web/components/templates/dashboard/dashboardPage.tsx
- web/components/templates/requestsV2/viewColumns.tsx
- **tes**
- **x**
- **fix requests graph time bug**
- **cols**
> view-col-ux

- costs/src/providers/mappings.ts
Reverts Helicone/helicone#1597
> Revert "Fix urls"

- costs/src/providers/mappings.ts
- web/packages/cost/providers/mappings.ts
- worker/src/packages/cost/providers/mappings.ts
Reverts Helicone/helicone#1598
> Revert "Revert "Fix urls""

- web/components/shared/themed/themedModal.tsx
- web/components/templates/requestsV2/costPill.tsx
themed modal fixes + cost unsupported link
> Themed modal fixes + cost unsupported link

- web/components/shared/themed/themedAdvancedFilters.tsx
fix showing create filter button
> fix showing create filter button

- web/components/shared/themed/themedAdvancedFilters.tsx
- web/components/templates/dashboard/dashboardPage.tsx
- web/pages/api/organization/[id]/create_filter.ts
- web/pages/api/organization/[id]/layout.ts
- web/pages/api/organization/[id]/update_filter.ts
- web/pages/dashboard.tsx
- web/services/lib/organization_layout/organization_layout.ts
Removed encoding and decoding for saved filters
> Removed encoding and decoding for saved filters

- tests/python_integration_tests.py
- valhalla/jawn/src/schema/types.d.ts
- worker/src/lib/dbLogger/DBLoggable.ts
- worker/src/lib/dbLogger/clickhouseLog.ts
- worker/src/lib/dbLogger/logResponse.ts
> Request ip null by default

- clickhouse/migrations/schema_27_country_code.sql
- clickhouse/migrations/schema_28_country_code_properties.sql
- clickhouse/migrations/schema_29_country_code_cache.sql
- supabase/migrations/20240328034713_country_code.sql
- valhalla/jawn/src/lib/db/database.types.ts
- web/supabase/database.types.ts
- worker/src/lib/HeliconeProxyRequest/forwarder.ts
- worker/src/lib/HeliconeProxyRequest/mapper.ts
- worker/src/lib/RequestWrapper.ts
- worker/src/lib/cache/cacheFunctions.ts
- worker/src/lib/db/clickhouse.ts
- worker/src/lib/dbLogger/DBLoggable.ts
- worker/src/lib/dbLogger/RequestResponseStore.ts
- worker/src/lib/dbLogger/clickhouseLog.ts
- worker/src/lib/dbLogger/logResponse.ts
- worker/supabase/database.types.ts
> Request country code

- valhalla/jawn/src/lib/shared/db/s3Client.ts
- valhalla/jawn/src/lib/shared/request/request.ts
- web/lib/api/db/s3Client.ts
- web/lib/api/request/request.ts
- worker/src/db/S3Client.ts
> S3 Request Id folder

- valhalla/jawn/nodemon.json
> Fixed genTypes.py

- web/components/shared/themed/table/filtersButton.tsx
- web/components/shared/themed/table/themedTableHeader.tsx
- web/components/shared/themed/table/themedTableV5.tsx
- web/components/shared/themed/themedAdvancedFilters.tsx
- web/components/shared/themed/themedTableHeader.tsx
- web/components/templates/cache/cachePage.tsx
- web/components/templates/dashboard/dashboardPage.tsx
- web/components/templates/dashboard/saveFilterButton.tsx
- web/components/templates/requestsV2/requestsPageV2.tsx
- web/components/templates/users/id/userIdPage.tsx
- web/pages/requests.tsx
- web/services/hooks/organization_layout.ts
Added Requests page persistent filters
> Requests page persistent filters

- supabase/migrations/20240403112012_assets.sql
> DB migration s3 image

- web/components/shared/loadingAnimation.tsx
- web/components/templates/requestsV2/requestsPageV2.tsx
- **remove jawn from initial request id check**
- **remove console logs**
> request-drawer-refresh

- valhalla/jawn/src/lib/shared/db/dbExecute.ts
> Revert supabase ssl changes

- worker/package-lock.json
- worker/package.json
- worker/src/lib/HeliconeProxyRequest/ProxyForwarder.ts
- worker/src/lib/clients/PosthogClient.ts
- worker/src/lib/dbLogger/DBLoggable.ts
- worker/src/lib/managers/AsyncLogManager.ts
- worker/src/lib/models/HeliconeHeaders.ts
> PostHog integration

- web/components/shared/themed/table/filtersButton.tsx
- web/components/templates/dashboard/dashboardPage.tsx
- web/components/templates/dashboard/saveFilterButton.tsx
- web/components/templates/properties/propertyPanel.tsx
- web/components/templates/requestsV2/requestsPageV2.tsx
- web/components/templates/users/userModal.tsx
> Reverted URL Encoded Filters

- worker/package.json
- worker/src/lib/clients/PosthogClient.ts
> Posthog package -> fetch

- worker/src/lib/models/HeliconeHeaders.ts
> Posthog property log

- web/components/templates/playground/playgroundPage.tsx
- web/components/templates/prompts/experiments/id/experimentIdPage.tsx
- web/components/templates/prompts/id/arrayDiffViewer.tsx
- web/components/templates/prompts/id/experimentForm.tsx
- web/components/templates/prompts/id/promptIdPage.tsx
- web/components/templates/prompts/id/promptNewExperiment.tsx
- web/components/templates/prompts/promptsPage.tsx
- web/components/templates/requests/chat.tsx
> exp-changes

- valhalla/jawn/src/lib/experiment/run.ts
Experiment provider key hotfix
> Experiment provider key hotfix

- docs/features/advanced-usage/llm-security.mdx
- added info about vulnerabilities with LLM apps 
- added code snippets for LLM security headers 
**Collapsed view**
**Expanded view**
> llm security docs update

- docs/swagger.json
- valhalla/jawn/src/controllers/public/experimentController.ts
- valhalla/jawn/src/lib/stores/experimentStore.ts
- valhalla/jawn/src/tsoa-build/public/routes.ts
- valhalla/jawn/src/tsoa-build/public/swagger.json
- web/lib/clients/jawnTypes/public.ts
> BE Scores Aggregation

- docs/getting-started/integration-method/gateway-fallbacks.mdx
- updated the content and structure of this doc 
- included code snippets where needed.
> updated Gateway Fallbacks doc

- valhalla/jawn/src/controllers/public/requestController.ts
- valhalla/jawn/src/lib/db/ClickhouseWrapper.ts
- valhalla/jawn/src/lib/handlers/LoggingHandler.ts
- valhalla/jawn/src/lib/stores/ScoreStore.ts
- valhalla/jawn/src/managers/score/ScoreManager.ts
> Score writing in Clickhouse

- web/components/templates/dashboard/useDashboardPage.tsx
- web/services/hooks/models.tsx
- web/services/lib/filters/filters.ts
> Fixed Models graph 

- docs/swagger.json
- valhalla/jawn/src/tsoa-build/private/swagger.json
- valhalla/jawn/src/tsoa-build/public/swagger.json
- valhalla/jawn/tsoa-private.json
- valhalla/jawn/tsoa-public.json
- web/components/shared/themed/themedAdvancedFilters.tsx
> Feedback filters fix

- web/components/templates/prompts/experiments/scoresTable.tsx
> Experiment overview hotfix

- valhalla/jawn/src/lib/clients/postHogClient.ts
- valhalla/jawn/src/lib/handlers/PostHogHandler.ts
Added helicone back link to posthog
> Added helicone back link to posthog

- web/components/templates/dashboard/dashboardPage.tsx
- web/components/templates/dashboard/panels/countryPanel.tsx
- web/services/hooks/country.tsx
> Country panel filters

- web/components/templates/playground/playgroundPage.tsx
- web/pages/api/anthropic/chat/index.ts
- **duplicate fixes**
- **claude system fix**
> playground-fixes

- web/services/lib/filters/frontendFilterDefs.ts
> request-id filter on the request page

- docs/getting-started/integration-method/openrouter.mdx
- valhalla/jawn/src/utils/helpers.ts
> Documented the streaming + costs support in OpenRouter integration

- docs/swagger.json
- supabase/migrations/20240524014813_scores_value_type.sql
- valhalla/jawn/src/controllers/public/requestController.ts
- valhalla/jawn/src/lib/stores/ScoreStore.ts
- valhalla/jawn/src/managers/score/ScoreManager.ts
- valhalla/jawn/src/tsoa-build/public/routes.ts
- valhalla/jawn/src/tsoa-build/public/swagger.json
- web/lib/clients/jawnTypes/public.ts
> Score value type

- valhalla/jawn/src/lib/stores/experimentStore.ts
- web/components/templates/prompts/experiments/scoresTable.tsx
> Latency score + fix

- docs/getting-started/quick-start.mdx
- updated redirect links 
- added gemini
> updated redirect links from getting started

- docs/getting-started/quick-start.mdx
- docs/integrations/anthropic/javascript.mdx
- docs/integrations/azure/curl.mdx
- docs/integrations/azure/javascript.mdx
- docs/integrations/gemini/api/javascript.mdx
- docs/integrations/gemini/vertex/javascript.mdx
- docs/integrations/groq/curl.mdx
- docs/integrations/openai/curl.mdx
- docs/integrations/openai/javascript.mdx
- docs/mint.json
- added cURL to openAI and Azure
- replaced "Node.js" with "Javascript" for all integration docs
> Update integration docs 

- valhalla/jawn/src/lib/stores/LogStore.ts
> search records fix

- valhalla/jawn/src/lib/stores/LogStore.ts
> Truncate tsvector in PG

- valhalla/jawn/src/lib/handlers/LoggingHandler.ts
Removed nulls from tsvector text
> Removed nulls from tsvector text

- valhalla/jawn/src/lib/stores/LogStore.ts
> duplicated search records

- worker/src/lib/util/cache/cacheFunctions.ts
- Removed 10ms delay;
- added cache timeout of 2 sec, hits actual endpoint if cache not returned within 2 sec.
> Impl cache timeout

- docs/mint.json
- docs/use-cases/bill-by-usage.mdx
- docs/use-cases/enable-stream-usage.mdx
- docs/use-cases/experiments.mdx
- docs/use-cases/getting-user-requests.mdx
- docs/use-cases/segmentation.mdx
- added a new guide for correcting cost cal for streaming 
- changed the title of some other guides to be consistent and more natural
> added stream-usage doc

- web/components/templates/sessions/nameSelection.tsx
> added sessions FE changes

- web/components/templates/playground/chatPlayground.tsx
- web/components/templates/playground/playgroundPage.tsx
- web/pages/api/anthropic/chat/index.ts
- web/pages/api/open_ai/chat/index.ts
- web/services/lib/providers/anthropic.ts
- web/services/lib/providers/openAI.ts
- Lets users use their finetuned models in playground.
- Interface for users to use their own keys (required for ft model access)
> feat: Finetuned models in playground

- web/components/templates/requests/chat.tsx
- web/components/templates/requestsV2/builder/abstractRequestBuilder.tsx
- web/components/templates/requestsV2/builder/chatGPTBuilder.tsx
- web/components/templates/sessions/sessionId/Chat/ChatSession.tsx
- web/components/templates/sessions/sessionId/TabSelector.tsx
- web/public/sitemap-0.xml
updates 
- updated the UI
- the card is now responsive
future ticket: clicking on a custom property should take you to the corresponding custom properties page
> sessions card ui updated

- costs/__tests__/ensureOnlyOne.ts
- costs/package-lock.json
- costs/src/providers/groq/index.ts
- costs/src/providers/mappings.ts
- valhalla/jawn/src/packages/cost/providers/groq/index.ts
- valhalla/jawn/src/packages/cost/providers/mappings.ts
- web/packages/cost/providers/groq/index.ts
- web/packages/cost/providers/mappings.ts
- worker/src/packages/cost/providers/groq/index.ts
- worker/src/packages/cost/providers/mappings.ts
Update Groq Costs:
Models updated: 
- Gemma 7b It / [gemma-7b-it]
- Mixtral 8x7b 32768 / [mixtral-8x7b-32768]
Models added:
- Gemma2 9b It / [gemma2-9b-it]
- Llama3 70b 8192 / [llama3-70b-8192]
- Llama3 8b 8192 / [llama3-8b-8192]
- Llama3 Groq 70b 8192 Tool Use Preview / [llama3-groq-70b-8192-tool-use-preview]
- Llama3 Groq 8b 8192 Tool Use Preview / [llama3-groq-8b-8192-tool-use-preview]
> update groq costs

- bifrost/app/blog/page.tsx
- whoops, the previous blog disappeared. 
- just added it back
> added back the product hunt blog

- costs/src/providers/openrouter/index.ts
> Added GPT-4o-mini costs

- web/components/templates/prompts/promptsPage.tsx
- web/components/templates/welcome/steps/features.tsx
Reverts Helicone/helicone#2576
> Revert "[ENG-1099] Update to use new Helicone Prompt library"

- web/components/templates/requestsV2/requestRow.tsx
> fix empty state

- bifrost/app/blog/blogs/slash-llm-cost/metadata.json
- bifrost/app/blog/blogs/slash-llm-cost/src.mdx
> Blog: Slash LLM cost - added keywords

- bifrost/app/blog/blogs/best-datadog-alternative-for-llm/metadata.json
- bifrost/app/blog/blogs/best-datadog-alternative-for-llm/src.mdx
- bifrost/app/blog/page.tsx
> Blog: Datadog add keywords

- bifrost/app/page.tsx
> Add ph, yc, gh stars badges

- web/components/templates/requests/chatComponent/chat.tsx
- web/components/templates/requests/chatComponent/chatTopBar.tsx
- web/components/templates/requests/completion.tsx
- web/components/templates/requestsV2/builder/chatBuilder.tsx
- web/components/templates/requestsV2/builder/chatGPTBuilder.tsx
- web/components/templates/requestsV2/statusBadge.tsx
- web/components/templates/sessions/sessionId/SessionContent.tsx
- web/components/templates/sessions/sessionId/SessionContentV2.tsx
- web/components/templates/sessions/sessionId/Span.tsx
- web/components/templates/sessions/sessionId/Tree/PathNode.tsx
- web/components/templates/sessions/sessionId/Tree/RequestNode.tsx
- web/components/templates/sessions/sessionId/Tree/Tree.tsx
- web/components/templates/sessions/sessionId/Tree/TreeView.tsx
- web/components/templates/sessions/sessionId/breadCrumbV2.tsx
- web/components/ui/hoverCard.tsx
- web/components/ui/tabs.tsx
- web/package.json
- web/pages/sessions/[session_id].tsx
- web/styles/index.css
- web/yarn.lock
Redesign of the specific session pages
https://www.loom.com/share/cc3ed9fc4d69462d9a96a29e91d8fa18?sid=7ade96be-42f5-4c13-a53b-6f1fb3952e54
https://www.loom.com/share/0b49d9a9137b401d96ad700441ae9486
> Session page redesign

- web/components/templates/prompts/promptsPage.tsx
> update prompts code in "Need Prompts" alert

- docs/swagger.json
- helicone-node/api/generatedTypes/public.ts
- valhalla/jawn/src/controllers/private/adminController.ts
- valhalla/jawn/src/tsoa-build/private/routes.ts
- valhalla/jawn/src/tsoa-build/private/swagger.json
- valhalla/jawn/src/tsoa-build/public/routes.ts
- valhalla/jawn/src/tsoa-build/public/swagger.json
- web/components/layout/admin/adminLayout.tsx
- web/components/templates/admin/adminFeatureFlags.tsx
- web/lib/clients/jawnTypes/private.ts
- web/lib/clients/jawnTypes/public.ts
- web/pages/admin/feature-flags.tsx
Allows the ability to enable and disable feature flags in the admin panel
> added feature flag config

- bifrost/app/rss/changelog.xml/route.ts
- bifrost/package-lock.json
- bifrost/package.json
- bifrost/yarn.lock
/rss/changelog.xml
https://nextjs.org/docs/app/building-your-application/deploying/static-exports#route-handlers (route handlers render a static response when `next build` runs so this will render a static xml file)
> Add rss feed to changelog

- bifrost/app/llm-cost/CalculatorInfo.tsx
- bifrost/app/llm-cost/ModelPriceCalculator.tsx
- bifrost/components/ui/themedTextDropDown.tsx
> added styling to LLM Costs page

- web/components/templates/prompts/experiments/table/ExperimentTable.tsx
- web/components/templates/prompts/experiments/table/HypothesisCellRenderer.tsx
- web/components/templates/prompts/id/promptPlayground.tsx
https://www.loom.com/share/278e6f55819e488a80f42b700a1d9c09?sid=d2772a03-25ee-434c-9204-0e083427c165
> Experiments UI fixes

- docs/swagger.json
- valhalla/jawn/src/controllers/public/experimentController.ts
- valhalla/jawn/src/lib/experiment/run.ts
- valhalla/jawn/src/lib/stores/experimentStore.ts
- valhalla/jawn/src/loops/experiments.ts
- valhalla/jawn/src/managers/experiment/ExperimentManager.ts
- valhalla/jawn/src/tsoa-build/private/routes.ts
- valhalla/jawn/src/tsoa-build/private/swagger.json
- valhalla/jawn/src/tsoa-build/public/routes.ts
- valhalla/jawn/src/tsoa-build/public/swagger.json
- web/components/templates/requestsV2/requestRow.tsx
- web/lib/clients/jawnTypes/private.ts
- web/lib/clients/jawnTypes/public.ts
Adds the following experiment to the table
> added experiment id to request drawer and link to table

- bifrost/app/blog/[file-path]/page.tsx
- bifrost/components/blog/BottomLine.tsx
- bifrost/components/blog/CallToAction.tsx
- bifrost/components/blog/TwitterShareButton.tsx
- bifrost/mdx-components.tsx
> added custom components for blogs

- web/components/templates/organization/plan/proBillingPage.tsx
undoes some of the changes here: 
https://github.com/Helicone/helicone/pull/2667
But was not able to reproduce the same issue. so i think we are okay :)
> fix pricing page states

- valhalla/jawn/src/lib/handlers/LytixHandler.ts
Sorry for this PR, they also wanted these two parameters. 
Copying the logic here https://github.com/Helicone/helicone/pull/2949
> Add sessionPath and name to lytix payload

- web/components/templates/sessions/sessionId/Tree/RequestNode.tsx
- web/components/templates/sessions/sessionId/Tree/Tree.tsx
> labels on sessions if path ends

- bifrost/components/layout/footer.tsx
> Footer seo change

- docs/integrations/openai/crewai.mdx
Updating CewAI integration documentation with native crewai SDK implementation,
> Updating CrewAI integration docs

- docs/getting-started/integration-method/crewai.mdx
- docs/mint.json
> Update documentation for Crew AI integration

- bifrost/app/blog/blogs/llm-api-providers/metadata.json
- bifrost/app/blog/blogs/llm-api-providers/src.mdx
- added internal links 
- updated heading hierarchy
> Blog update: Ai inference providers

- docs/guides/applications/resell-a-model.mdx
> docs: update resell-a-model.mdx

- web/components/shared/CreateNewEvaluator/LLMEvaluatorConfigForm.tsx
- web/components/templates/evals/details/LLMAsJudgeEvaluatorDetails.tsx
- web/components/templates/evals/panels/EditPanel.tsx
> Fix eval state

- web/components/layout/auth/DesktopSidebar.tsx
- web/components/layout/orgDropdown.tsx
BEFORE:
- Scroll appears along both axis
- Padding not set resulting in poor centering of orgDropdown component
- Long org name truncate causing icon overflow
https://github.com/user-attachments/assets/cb9f2bfe-3c04-4677-91fb-ed11108ef523
AFTER:
- Fixed scroll, padding, and truncate
https://github.com/user-attachments/assets/c73eea46-2bc3-4deb-9b92-4205609d6feb
> Fix: Spacing, truncate, and scroll css in DesktopSidebar component

- web/components/layout/auth/DesktopSidebar.tsx
> Fix: "Ready to Integrate" Button removed on accident [MERGE ASAP]

- web/components/layout/auth/authLayout.tsx
- web/components/shared/prompts/PromptPanels.tsx
- web/components/templates/prompts/id/promptIdPage.tsx
- web/utils/variables.ts
- Fix: Bad message state resulting in bad or loss of structure
- Revert: Classname changed by mistake on yesterdays PR broke overflow
> Fix: Bad Prompt Editor Message States + className Revert

- web/components/templates/prompts/id/promptIdPage.tsx
- web/types/prompt-state.ts
- web/utils/messages.ts
- Now passing templateData.content optionally + handeling it better
> Fix: Assistant API prompt loading

- docs/features/prompts.mdx
> Docs: Prompts Python Package

- packages/cost/providers/openai/index.ts
See: https://openai.com/api/pricing/
> Added o3-mini costs

- docs/getting-started/self-host/docker.mdx
Hello
While reading the document, there was a part that was unclear, so I edited that part to make it more consistent with my understanding.
> add the full command for local deployment

- bifrost/app/blog/blogs/llm-observability/metadata.json
- bifrost/app/blog/blogs/llm-observability/src.mdx
- added internal links 
- improved content
> [ready to merge] Llm observability blog

- bifrost/app/blog/blogs/debugging-chatbots-and-ai-agents-with-sessions/metadata.json
- bifrost/app/blog/blogs/debugging-chatbots-and-ai-agents-with-sessions/src.mdx
> Blog update: debug agents with sessions

- bifrost/lib/clients/jawnTypes/private.ts
- bifrost/lib/clients/jawnTypes/public.ts
- docs/swagger.json
- valhalla/jawn/src/controllers/public/experimentV2Controller.ts
- valhalla/jawn/src/managers/experiment/ExperimentV2Manager.ts
- valhalla/jawn/src/tsoa-build/private/routes.ts
- valhalla/jawn/src/tsoa-build/private/swagger.json
- valhalla/jawn/src/tsoa-build/public/routes.ts
- valhalla/jawn/src/tsoa-build/public/swagger.json
- web/components/templates/prompts/experiments/table/ExperimentTable.tsx
- web/components/templates/prompts/experiments/table/cells/HypothesisCellRenderer.tsx
- web/components/templates/prompts/experiments/table/components/tableElementsRenderer.tsx
- web/components/templates/prompts/experiments/table/hooks/useExperimentTable.tsx
- web/components/templates/prompts/id/promptChatRow.tsx
- web/components/templates/prompts/id/promptPlayground.tsx
- web/components/ui/checkbox.tsx
- web/lib/clients/jawnTypes/private.ts
- web/lib/clients/jawnTypes/public.ts
https://github.com/user-attachments/assets/263a1d59-6278-4d94-9a29-8528b98cf297
> experiments delete rows

- packages/llm-mapper/mappers/openai/realtime.ts
- packages/llm-mapper/utils/getMappedContent.ts
- valhalla/jawn/src/packages/llm-mapper/mappers/openai/realtime.ts
- valhalla/jawn/src/packages/llm-mapper/utils/getMappedContent.ts
- web/components/templates/requests/components/realtime/Realtime.tsx
- web/packages/llm-mapper/mappers/openai/realtime.ts
- web/packages/llm-mapper/utils/getMappedContent.ts
Fix: Improved lllm-mapper sanitization, fixed realtime mapper data guards
> Realtime fixes 2

- examples/qawolf-ws/index.ts
- packages/llm-mapper/mappers/openai/realtime.ts
- valhalla/jawn/src/lib/proxy/WebSocketProxyRequestHandler.ts
- valhalla/jawn/src/packages/llm-mapper/mappers/openai/realtime.ts
- web/components/templates/requests/components/realtime/Realtime.tsx
- web/packages/llm-mapper/mappers/openai/realtime.ts
Fix: Corrected mapping of conversation.item.input_audio_transcription.completed transcript
Update: Improved Realtime session updates and header styles
Fix: Helicone properties correctly given to log now
Misc: examples improvement
> Realtime fixes 3

- web/components/templates/playground/functionButton.tsx
- web/components/templates/playground/playgroundPage.tsx
NOTE: Not guaranteed to work when "Submit" is pressed. This is temporary only.
> Temp Fix: Now loading into playground

- packages/cost/providers/google/index.ts
See: https://ai.google.dev/pricing#2_0flash
> Added gemini 2.0 flash costs

- web/components/shared/prompts/AutoImprove.tsx
- web/components/shared/universal/Popup.tsx
- web/components/templates/prompts/id/promptIdPage.tsx
- web/pages/api/llm/index.ts
- Fix: Prefer Fireworks provider for R1 calls
- Update: Improved Auto-improve looks
> Auto improve fixes

- web/components/shared/prompts/ParametersPanel.tsx
- web/components/templates/prompts/id/promptIdPage.tsx
- web/types/prompt-state.ts
> Fix: legacy loading of prompts

- bifrost/app/blog/blogs/grok-3-benchmark-comparison/src.mdx
- grok 3 is now free for a while - just made the update
> Blog: Grok 3 update

- web/components/templates/prompts/id/PromptEditor.tsx
- web/components/templates/prompts/promptsPage.tsx
- web/pages/prompts/new/index.tsx
Fix: create prompt button using hook directly again
Fix: Now always creating a prompt in /new page
Fix: canRun is less strict
> Fix prompts canRun and new flow

- docs/integrations/gemini/api/javascript.mdx
Fixes #3310. Existing example for JS did not work. I updated the example to use https://github.com/google-gemini/generative-ai-js and made sure it worked.
> Fix gemini js example

- web/components/shared/themed/table/themedTable.tsx
- web/components/templates/sessions/sessionDetails.tsx
- web/components/templates/sessions/sessionId/SessionContent.tsx
- web/components/templates/sessions/sessionsPage.tsx
- web/lib/sessions/realtimeSession.ts
Fix: Simpler and safer isRealtimeSession detection
Fix: Changed sessions onRowSelect to new, rowLink themedTable param, ensuring minimum code and no effect on other tables
> Realtime fixes 4

- bifrost/app/blog/blogs/chain-of-draft/src.mdx
- bifrost/components/blog/TableOfContents.tsx
- bifrost/components/ui/typography.tsx
- bifrost/mdx-components.tsx
> added a table of content component to blogs

- web/components/shared/prompts/PromptBox.tsx
- web/components/shared/prompts/ResponsePanel.tsx
- web/components/templates/prompts/id/PromptEditor.tsx
- worker/src/lib/RequestWrapper.ts
- worker/src/lib/models/HeliconeHeaders.ts
- worker/src/lib/models/HeliconeProxyRequest.ts
- worker/src/routers/gatewayRouter.ts
- worker/src/routers/generateRouter.ts
- Update: Now also saving Helicone-Prompt-Version
- Update: prompt_input_records are now being successfully saved with the generate api
- Fix: prose causing lots of buggy markdown, replaced with custom components
- Fix: wrong toolbar generate provider
- Fix: Loading a prompt does not load the inputs into state
- Misc: Improved button copy from Cole feedback
> Prompts 3b: Various updates and fixes

- valhalla/jawn/src/controllers/public/experimentV2Controller.ts
- valhalla/jawn/src/managers/prompt/PromptManager.ts
> hotfix: empty extra row created on new experiment from request(without prompt)

- web/components/shared/helicone/EmptyStateCard.tsx
- web/components/templates/prompts/id/PromptEditor.tsx
- web/components/templates/prompts/promptsPage.tsx
- web/components/ui/button.tsx
- web/yarn.lock
Fix: Wrong EmptyStateCard config for prompts
Refactor: Streamlined prompt editor mode validation
> Hotfix: Various Prompt Related fixes

- web/components/templates/requests/components/chatComponent/jsonView.tsx
- web/components/templates/requests/components/chatComponent/single/JsonRenderer.tsx
JSON view uses the new JSON renderer and renders the JSON nicely and also makes the string new lines better
> JSON view - improved JSON view to have better rendering and copying stuff

- bifrost/app/blog/[file-path]/page.tsx
> removed linking in headings

- bifrost/packages/cost/unified/models.ts
- bifrost/packages/cost/unified/providers.ts
- bifrost/packages/cost/unified/types.ts
- packages/cost/unified/models.ts
- packages/cost/unified/providers.ts
- packages/cost/unified/types.ts
- valhalla/jawn/src/packages/cost/unified/models.ts
- valhalla/jawn/src/packages/cost/unified/providers.ts
- valhalla/jawn/src/packages/cost/unified/types.ts
- web/components/shared/prompts/ParametersPanel.tsx
- web/components/templates/prompts/id/DeployDialog.tsx
- web/components/templates/prompts/id/PromptEditor.tsx
- web/packages/cost/unified/models.ts
- web/packages/cost/unified/providers.ts
- web/packages/cost/unified/types.ts
- web/utils/promptDeploy.ts
- worker/src/packages/cost/unified/models.ts
- worker/src/packages/cost/unified/providers.ts
- worker/src/packages/cost/unified/types.ts
New: Deepseek and Meta models added to prompts providers/models
> New: Deepseek and Meta models support in unified providers/models

- examples/qawolf-ws/index.ts
- packages/llm-mapper/mappers/openai/realtime.ts
- valhalla/jawn/src/index.ts
- valhalla/jawn/src/lib/proxy/WebSocketProxyForwarder.ts
- web/components/templates/requests/components/realtime/Realtime.tsx
- web/utils/audio.ts
New: Azure realtime support
Fix: Skips conversion to WAV if already detected as WAV
> Realtime: Azure support and WAV detection

- tests/e2e_suite.py
- valhalla/jawn/src/lib/shared/bodyProcessors/anthropicStreamBodyProcessor.ts
https://linear.app/helicone/issue/ENG-1418/%5Balai%5D-streaming-claude-not-working-for-json-returns
https://app.usepylon.com/issues?conversationID=b8ab220a-e6ec-4620-8677-f30fcaca2fac
> Fix: Anthropic tool streaming processor + test [ENG-1418]

- bifrost/app/blog/blogs/ai-agent-builders/metadata.json
- bifrost/app/blog/blogs/ai-agent-builders/src.mdx
- bifrost/app/blog/blogs/llm-api-providers/metadata.json
- bifrost/app/blog/blogs/llm-api-providers/src.mdx
1. llm api provider 
- updated seo title (what appears on google) 
- cleaned up fluff
- link from table to corresponding section
2. ai agent frameworks
- updated seo title
- added CTA 
- link from table to corresponding section
> Conversion minor fixes

- valhalla/jawn/src/managers/inputs/InputsManager.ts
- Fixes Inputs import in Prompts
- Might also fix recent Experiments issues
> Hotfix: InputsManager getInputs() query was broken recently

- packages/cost/providers/openai/index.ts
See: https://openai.com/api/pricing/
> Added o4-mini

- bifrost/components/layout/navbar.tsx
- new: "resources" and "tools" dropdown UI is now more modern
- new: hamburger menu for mobile view is now sectioned better 
- fixed: hover target for "resources" and "tools" is larger
- update: instead of on click for dropdown, it's now hover for better UX
> Navbar update: cleaner UI of both mobile/web view

- bifrost/components/layout/navbar.tsx
- added back sign in and sign up in mobile view
> added signin/signup back

- web/package.json
- web/yarn.lock
- Rare to reproduce, but this is my best guess after testing other options.
> Potential fix: Upped @radix-ui/react-checkbox version (checkbox hitbox bug)

- web/components/shared/themed/table/exportButton.tsx
- web/components/templates/sessions/sessionId/SessionContent.tsx
- web/components/templates/sessions/sessionId/Span.tsx
- web/components/templates/sessions/sessionsPage.tsx
- web/pages/sessions.tsx
- session clickable
- pixel pushes
> [1539] Slight Clean up for bug bash items

- valhalla/jawn/src/lib/clients/HeliconeQuequeProducer.ts
- valhalla/jawn/src/lib/proxy/ReadableInterceptor.ts
Default to no msg producer if Kafka/S3 not specified
> ENG-1582 default to no producer, allow specifying kafka/s3

- bifrost/components/home/FAQ.tsx
- added more FAQ to answer conversion-specific questions 
- updated layout to be `md:flex-row` for better reading experience
> updated FAQ on landing page

- bifrost/lib/clients/jawnTypes/public.ts
- docs/swagger.json
- valhalla/jawn/src/controllers/public/sessionController.ts
- valhalla/jawn/src/lib/shared/filters/timeFilter.ts
- valhalla/jawn/src/managers/SessionManager.ts
- valhalla/jawn/src/tsoa-build/public/routes.ts
- valhalla/jawn/src/tsoa-build/public/swagger.json
- web/components/admin/InvoiceTable.tsx
- web/components/templates/admin/adminProjections.tsx
- web/components/templates/sessions/SessionMetrics.tsx
- web/lib/clients/jawnTypes/public.ts
- deploy backend first and then frontend
> [ENG-1581] Add backend changes for Session Metrics Filters

- web/components/templates/sessions/sessionsPage.tsx
- search bar for sessions
- sorted by last_used
- Request session names async when typing in the search bar
Can test if you have >50 session names - typing in search will reveal 50 that might not have been in originally queried 50
> [ENG-1580] Searching + Sorting Sessions

- bifrost/lib/clients/jawnTypes/private.ts
- bifrost/lib/clients/jawnTypes/public.ts
- docs/swagger.json
- valhalla/jawn/src/controllers/public/sessionController.ts
- valhalla/jawn/src/managers/SessionManager.ts
- valhalla/jawn/src/managers/helpers/percentileDistributions.ts
- valhalla/jawn/src/tsoa-build/private/routes.ts
- valhalla/jawn/src/tsoa-build/private/swagger.json
- valhalla/jawn/src/tsoa-build/public/routes.ts
- valhalla/jawn/src/tsoa-build/public/swagger.json
- web/lib/clients/jawnTypes/private.ts
- web/lib/clients/jawnTypes/public.ts
- take the average for cost, duration, and request count
> [ENG-1596] Add Session Metrics Average

- bifrost/components/customers/CaseStudiesCTA.tsx
> fixed alignment issue in footer

- web/components/templates/sessions/SessionMetrics.tsx
- web/filterAST/components/FilterConditionNode.tsx
- web/services/hooks/sessions.tsx
> [Eng-1598] Session Average QA Wolf Frontend

- examples/qawolf-ws/index.ts
- valhalla/jawn/src/lib/proxy/DBLoggable.ts
- valhalla/jawn/src/lib/proxy/WebSocketProxyForwarder.ts
- valhalla/jawn/src/lib/proxy/WebSocketProxyRequestHandler.ts
- valhalla/jawn/src/packages/llm-mapper/utils/getMappedContent.ts
- web/components/templates/requests/components/Realtime.tsx
- web/lib/sessions/realtimeSession.ts
- Modify the Realtime Websocket proxy to log on 15 second intervals rather than waiting for the ws to close. Ensure that the logging is done with the same requestId as its an upsert op
- Memoize some vars in Realtime (was infinitely console log wailing before)
- also fix incorrect filtering in `Realtime.tsx`, causing the last message/turn of the session to not be displayed in the "Rendered" mode
> [ENG-1606] Live Session Updates

- web/components/templates/requests/components/Realtime.tsx
- web/lib/sessions/realtimeSession.ts
> [ENG-1634] Colour bars in realtime sessions by type

- .github/workflows/jawn-deployment.yml
- need to set the environment variables in github
- will need to test
- only able to deploy main branch
Update Docker build configuration for Jawn deployment workflow
> [ENG-1592] Add Github Actions for Manual Deployment

- web/components/templates/requests/RequestDrawer.tsx
only make the top row/section sticky
> [ENG-1625] Only sticky request info on scroll

- .gitignore
- docs/getting-started/self-host/manual.mdx
- valhalla/jawn/.env.example
- web/.env.example
- web/.gitignore
- worker/src/lib/clients/ProviderClient.ts
For manual hosting and self-hosting, flexible
> [ENG-1652] better docs + env files

- web/components/templates/sessions/sessionId/SessionContent.tsx
- web/components/templates/sessions/sessionId/Timeline/SessionTimelineTable.tsx
> [ENG-1587] Add Error Mapping + Session Bar Fix

- web/components/shared/themed/themedTimeFilterShadCN.tsx
Reverts Helicone/helicone#3760
> Revert "[ENG-1568] Make predefined ranges be ahead by a day to show new ones"

- docs/integrations/openai/curl.mdx
- docs/integrations/openai/langchain.mdx
- docs/integrations/openai/llamaindex.mdx
- docs/mint.json
- docs/other-integrations/dify.mdx
- docs/snippets/strings.mdx
1. **Title standardization**
Integration titles updated to follow a consistent format:
- Native SDKs are titled
- Access through third-parties get a "with" between them
- "OpenAI cURL Integration" → "OpenAI with cURL"
- "LangChain OpenAI" → "OpenAI with LangChain"
- "OpenAI SDK with Javascript" → "OpenAI JS SDK"
2. **Navigation alphabetization**
- Alphabetized names of providers accurately
- Alphabetized dropdowns inside the providers
> Alphabetization & title standarization

- web/components/shared/themed/demo/courseGenerator.tsx
- web/components/shared/themed/demo/textbookCourse.tsx
- web/components/shared/themed/table/themedTable.tsx
- web/components/templates/requests/RequestDrawer.tsx
- web/components/templates/requests/RequestsPage.tsx
- web/components/templates/sessions/sessionsPage.tsx
- web/pages/sessions/[name]/[session_id].tsx
- web/services/hooks/dataset/selectMode.tsx
- web/services/hooks/requests.tsx
- for helicone tusk, theres a bug if there multiple session_ids with different session names which leads to a random session name
> [AMF-1699] Add Session Name as a higher cardinality in UI

- web/components/templates/alerts/alertsPage.tsx
> fix: alerts page

- docs/integrations/azure/curl.mdx
- docs/integrations/azure/javascript.mdx
- docs/integrations/azure/langchain.mdx
- docs/integrations/azure/python.mdx
- docs/snippets/strings.mdx
- Standardized Azure OpenAI integration documentation across all supported languages (JavaScript, Python, LangChain, and cURL)
- Updated Azure endpoint URLs to use the correct format (`[AZURE_DOMAIN].azure.com`)
- Consolidated Azure OpenAI documentation link into a reusable string component
- Improved code examples with clearer parameter placeholders and comments
- Removed duplicate documentation text and replaced with consistent component usage
- Updated model and deployment name placeholders for better clarity
> Azure OpenAI Integration Documentation Updates

- web/components/templates/sessions/sessionId/SessionContent.tsx
> [ENG-1725] Show ids by session Id

- web/components/templates/requests/components/Realtime.tsx
- web/components/templates/sessions/sessionId/Tree/TreeView.tsx
- fix user deleted message collapse
- when clicking on request it shouldnt resize
- remove opacity
> [ENG-1842] Make opacity gone and session drawing to not resize on clicking request

- examples/anthropic/index.ts
- examples/anthropic/package.json
- examples/anthropic/yarn.lock
- packages/cost/costCalc.ts
- valhalla/jawn/src/lib/shared/bodyProcessors/anthropicStreamBodyProcessor.ts
- worker/src/lib/dbLogger/streamParsers/anthropicStreamParser.ts
Jawn: change to get finalized output tokens instead of initial 1 count
Worker: update parser for sonnet/opus 4
> bug: [ENG-1915] Fix anthropic stream parsing

- valhalla/jawn/src/lib/clients/sqsConsumers/sqsConsumers.ts
- valhalla/jawn/src/lib/producers/sqsTypes.ts
- valhalla/jawn/src/workers/consumerInterface.ts
- valhalla/jawn/src/workers/sqsConsumer.ts
- worker/src/index.ts
- worker/src/lib/clients/RequestRateLimiter.ts
- worker/src/lib/clients/producers/DualProducer.ts
- worker/src/lib/clients/producers/HeliconeProducer.ts
- worker/src/lib/clients/producers/KafkaProducerImpl.ts
- worker/src/lib/clients/producers/SQSProducer.ts
- worker/src/lib/clients/producers/types.ts
- worker/src/lib/dbLogger/DBLoggable.ts
- bring back the old rate limiting logic but instead if they're rate limited, queue them to the lower priority queue
> [ENG-1887] Add Lower Priority Queue for SQS

- docs/features/experiments.mdx
- docs/getting-started/quick-start.mdx
- docs/guides/cookbooks/experiments.mdx
- docs/guides/overview.mdx
- docs/quick-start.mdx
- web/components/layout/auth/Sidebar.tsx
- web/components/shared/Deprecated.tsx
- web/components/templates/evals/EvaluatorsList.tsx
- web/components/templates/prompts/experiments/table/ExperimentTable.tsx
- web/components/templates/prompts/experiments/table/experimentsPage.tsx
- web/pages/evaluators/[id].tsx
- web/pages/evaluators/new.tsx
- **add deprecated alert to experiment and eval pages**
- **deprecated to docs**
> deprecate experiment evals

- docs/gateway/concepts/loadbalancing.mdx
- docs/gateway/concepts/model-mapping.mdx
- docs/gateway/concepts/providers.mdx
- docs/gateway/concepts/routers.mdx
- docs/gateway/concepts/secret-management.mdx
- docs/gateway/config.mdx
- docs/gateway/debugging/router-health.mdx
- docs/gateway/introduction.mdx
- docs/gateway/quickstart.mdx
Reverts Helicone/helicone#3954
> Revert "task: update docs for ai gateway"

- web/components/templates/playground/components/ModelParametersForm.tsx
- web/components/templates/playground/components/PlaygroundActions.tsx
- web/components/templates/playground/components/PlaygroundHeader.tsx
- web/components/templates/playground/components/PlaygroundMessagesPanel.tsx
- web/components/templates/playground/playgroundPage.tsx
- web/components/templates/requests/components/chatComponent/ChatMessageTopBar.tsx
- web/lib/api/llm/generate-stream.ts
- web/lib/api/llm/generate.ts
> bug: [ENG-2089] fix params not passing through

- docker/push_docker.sh
- docker/terraform/main.tf
Change from aigateway to ai-gateway for image names
> misc: Update repository name from aigateway to ai-gateway for ecr and dockerhub

- docs/docs.json
- docs/guides/cookbooks/helicone-evals-with-ragas.mdx
This doc shows how to export datasets for use with evaluations through Ragas.
> docs: Helicone evals with ragas

- clickhouse/migrations/schema_59_prompt_column.sql
Does not include logging, so itll just be a blank field on all requests when added. 
Will not be backfilling on old prompts.
> feat: [ENG-2031] Prompt column in CH requests RMT

- supabase/migrations/20250619011938_prompts_2025.sql
> feat: [ENG-2030] prompts (postgres)

- helicone-cron/src/client/SqsClient.ts
- helicone-cron/src/heartbeats/alertSqsCongestion.ts
- helicone-cron/src/index.ts
- also add to cloudflare and deploy
> feat: check low priority queue SQS cron

- bifrost/lib/clients/jawnTypes/private.ts
- bifrost/lib/clients/jawnTypes/public.ts
- docs/swagger.json
- valhalla/jawn/src/controllers/public/prompt2025Controller.ts
- valhalla/jawn/src/managers/prompt/PromptManager.ts
- valhalla/jawn/src/tsoa-build/private/routes.ts
- valhalla/jawn/src/tsoa-build/private/swagger.json
- valhalla/jawn/src/tsoa-build/public/routes.ts
- valhalla/jawn/src/tsoa-build/public/swagger.json
- web/components/templates/playground/components/PromptForm.tsx
- web/components/templates/playground/playgroundPage.tsx
- web/components/templates/prompts2025/PromptCard.tsx
- web/components/templates/prompts2025/PromptDetails.tsx
- web/components/templates/prompts2025/PromptVersionCard.tsx
- web/components/templates/prompts2025/PromptVersionHistory.tsx
- web/components/templates/prompts2025/promptsPage.tsx
- web/components/templates/prompts2025/timeUtils.ts
- web/lib/clients/jawnTypes/private.ts
- web/lib/clients/jawnTypes/public.ts
- web/pages/prompts2025/index.tsx
- web/services/hooks/prompts.tsx
> feat: [ENG-2033] Prompts display

- bifrost/lib/clients/jawnTypes/private.ts
- bifrost/lib/clients/jawnTypes/public.ts
- docs/swagger.json
- valhalla/jawn/src/controllers/public/prompt2025Controller.ts
- valhalla/jawn/src/managers/prompt/PromptManager.ts
- valhalla/jawn/src/tsoa-build/private/routes.ts
- valhalla/jawn/src/tsoa-build/private/swagger.json
- valhalla/jawn/src/tsoa-build/public/routes.ts
- valhalla/jawn/src/tsoa-build/public/swagger.json
- web/components/templates/playground/components/PlaygroundActions.tsx
- web/components/templates/playground/components/PlaygroundHeader.tsx
- web/components/templates/playground/components/PlaygroundMessagesPanel.tsx
- web/components/templates/playground/components/PromptForm.tsx
- web/components/templates/playground/playgroundPage.tsx
- web/components/templates/prompts2025/PromptDetails.tsx
- web/components/templates/prompts2025/PromptVersionCard.tsx
- web/components/templates/prompts2025/PromptVersionHistory.tsx
- web/components/templates/prompts2025/promptsPage.tsx
- web/lib/clients/jawnTypes/private.ts
- web/lib/clients/jawnTypes/public.ts
- web/services/hooks/prompts.tsx
> feat: [ENG-2067] Prompt versioning and saving

- docs/getting-started/self-host/docker.mdx
* update the docker run command to include repository name
> docs: Update docker run instructions

- helicone-cron/src/db/database.types.ts
- supabase/migrations/20250310003820_provider_keys_config_json.sql
- valhalla/jawn/src/lib/db/database.types.ts
- web/db/database.types.ts
- worker/supabase/database.types.ts
added this to a prev migration so that it doesn't run on prod
> feat: add a mock decrypted_provider_keys table

- web/components/onboarding/CodeIntegrationPage.tsx
This pull request enhances the `CodeIntegrationPage` component by introducing query invalidation to ensure fresh data is loaded when redirecting to the dashboard.
> fix: [ENG-2118] Invalidate queries to ensure immediate request fetch after onboarding

- valhalla/jawn/src/lib/handlers/ResponseBodyHandler.ts
- valhalla/jawn/src/lib/shared/bodyProcessors/llamaStreamBodyProcessor.ts
Adds a processor for Llama responses when streaming.
> feat: [ENG-2308] Llama Stream Processor

- packages/cost/providers/openrouter/index.ts
> feat: [ENG-2319] Openrouter claude 4 series costs

- web/components/templates/gateway/createRouterDialog.tsx
https://github.com/user-attachments/assets/9bca55c0-8bff-417f-a38f-83eea1533ff4
**What Changed:**
- Transformed basic router creation dialog into comprehensive configuration interface
- Added interactive sections for load balancing, caching, and rate limiting
**Features which can be configured:**
- Load balancing pre-configured with model-latency strategy
- Not having the option to configure this in the UI currently, but can be done in the YAML after creation
- Optional caching with configurable directives and buckets
- Per-API-key rate limiting with customizable capacity
> feat: better create router dialog ui

- packages/cost/index.ts
- remove behaviour that we fallback to other providers with the same model ID
> fix: prevent cost fallbacks to other providers

- packages/cost/index.ts
- web/components/templates/admin/panels/costBackfiller.tsx
updates so that if costs are 0 it doesn't generate invalid sql (admin backfiller)
> feat: [ENG-2350] Fix cost admin portal

- .dockerignore
- Dockerfile
- monitor_logs.sh
- supervisord.conf
This pull request introduces significant updates to the Docker configuration, logging, and build processes. The most notable changes include improvements to the `Dockerfile` for better caching and dependency management, and a fix to the AI gateway build allowing it to be built together and remotely without the need for a git worktree in the same repo.
* Overhauled `.dockerignore` to include standard patterns for ignoring development, build, and dependency files, improving Docker build performance and security.
* Updated the `Dockerfile` to:
- Specify the platform for the base image (`--platform=linux/amd64`).
- Optimize dependency installation by copying `package.json` files first for better caching and separating source code copying from dependency installation.
- Add new COPY …
> fix: ai gateway all in one, better caching

- docker/push_docker.sh
This pull request enhances the `docker/push_docker.sh` script to support multi-platform Docker builds using Docker Buildx. The key changes introduce a new `--platforms` option, set up Docker Buildx for multi-platform builds, and modify the build process to handle multiple platforms.
> fix: Support for both intel/amd(x86_64) image push

- packages/llm-mapper/types.ts
- packages/llm-mapper/utils/getMappedContent.ts
- valhalla/jawn/src/lib/stores/request/request.ts
- web/components/templates/requests/RequestDrawer.tsx
- web/filterAST/filterUIDefinitions/staticDefinitions.ts
- **feat: add router id to filter and requestDrawer**
- **fix: clickhouse query to include gateway router id and deployment target**
> feat: add router id to filter and requestDrawer

- docs/ai-gateway/config.mdx
- docs/docs.json
- docs/features/advanced-usage/prompts.mdx
- docs/features/prompts-legacy/editor.mdx
- docs/features/prompts-legacy/generate.mdx
- docs/features/prompts-legacy/import.mdx
Added docs for using the new Prompts! Covering:
- Composing and versioning prompts in the Helicone dashboard
- Completions on the prompts through the AI Gateway
> feat: [ENG-2331] Prompt docs

- docs/docs.json
- docs/features/advanced-usage/prompts.mdx
- docs/rest/prompts/delete-v1prompt-2025-promptid-versionid.mdx
- docs/rest/prompts/delete-v1prompt-2025-promptid.mdx
- docs/rest/prompts/get-v1prompt-2025-count.mdx
- docs/rest/prompts/get-v1prompt-2025-id-promptid.mdx
- docs/rest/prompts/get-v1prompt-2025-tags.mdx
- docs/rest/prompts/post-v1prompt-2025-id-promptid-rename.mdx
- docs/rest/prompts/post-v1prompt-2025-query-production-version.mdx
- docs/rest/prompts/post-v1prompt-2025-query-total-versions.mdx
- docs/rest/prompts/post-v1prompt-2025-query-version.mdx
- docs/rest/prompts/post-v1prompt-2025-query-versions.mdx
- docs/rest/prompts/post-v1prompt-2025-query.mdx
- docs/rest/prompts/post-v1prompt-2025-update-production-version.mdx
- docs/rest/prompts/post-v1prompt-2025-update.mdx
- docs/rest/prompts/post-v1prompt-2025.mdx
- packages/prompts/types.ts
- sdk/typescript/helpers/package-lock.json
- sdk/typescript/helpers/package.json
- sdk/typescript/helpers/prompts/HeliconePromptManager.ts
- sdk/typescript/helpers/prompts/prompts.ts
- valhalla/jawn/src/controllers/public/prompt2025Controller.ts
- Update helpers SDK with functions to pull prompt body by IDs and/or compile them
- Add docs explaining SDK additions and potential usage without AI Gateway
> feat: [ENG-2428] TS SDK for Prompts + Docs

- packages/filters/filters.ts
- valhalla/jawn/src/controllers/public/gatewayController.ts
- valhalla/jawn/src/managers/gatewayManager.ts
- valhalla/jawn/src/managers/request/RequestManager.ts
- web/components/templates/gateway/costOverTimeChart.tsx
- web/components/templates/gateway/defaultAIGateway.tsx
- web/components/templates/gateway/gatewayPage.tsx
- web/components/templates/gateway/gatewayRouterDetails.tsx
- web/components/templates/gateway/latencyOverTimeChart.tsx
- web/components/templates/gateway/myRouters.tsx
- web/components/templates/gateway/requestOverTimeChart.tsx
- web/components/templates/gateway/routerUseDialog.tsx
- web/components/templates/gateway/useGatewayRouterRequests.tsx
- web/components/templates/gateway/useGatewayRouterStats.tsx
Added a tab for the default ai gateway (`/ai`)
> feat: tab for default ai gateway

- docs/features/advanced-usage/prompts.mdx
Since input traces are now added to jawn + AI Gateway, updated the docs with benefits to using it.
> feat: [ENG-2494] Update prompts docs for traces

- bifrost/app/layout.tsx
Updated our Google metadata to reach better organic SEO based on description and what we're offering now.
> Fix metadata for SEO

- docs/docs.json
- docs/integrations/anthropic/claude-code.mdx
- docs/integrations/anthropic/curl.mdx
- docs/integrations/openai/javascript.mdx
- docs/snippets/strings.mdx
Generate documentation for Claude Code
> docs: claude code docs

- bifrost/lib/clients/jawnTypes/public.ts
- docs/swagger.json
- valhalla/jawn/src/controllers/public/gatewayController.ts
- valhalla/jawn/src/tsoa-build/public/routes.ts
- valhalla/jawn/src/tsoa-build/public/swagger.json
- web/components/templates/gateway/RouterConfigForm.tsx
- web/components/templates/gateway/createRouterPage.tsx
- web/components/templates/gateway/gatewayRouterDetails.tsx
- web/components/templates/gateway/routerConfigEditor.tsx
- web/components/templates/gateway/useRouterConfig.tsx
- web/lib/clients/jawnTypes/public.ts
https://github.com/user-attachments/assets/106052fe-d9b8-48de-a2b3-d219cf5e7714
This PR introduces a comprehensive router configuration system with a dual-editor interface (form and YAML) for managing gateway router settings. The changes include:
- **Enhanced Type Safety**: Updated `LatestRouterConfig` type to use `Json` instead of `string` for better type safety and validation
- **Dual Editor Interface**: Added form-based configuration editor alongside existing YAML editor for improved UX
- **Comprehensive Configuration Options**: Support for caching, rate limiting, retries, and load balancing with detailed form controls
- **Real-time Validation**: Integrated validation system to ensure configuration integrity before saving
- **Improved Developer Experience**: Better error handling and …
> feat: update router config using the ui

- web/components/templates/gateway/RouterConfigForm.tsx
- web/components/templates/gateway/routerConfigEditor.tsx
- web/components/templates/gateway/useGatewayRouter.tsx
- web/components/templates/gateway/useRouterConfig.tsx
Blocked by https://github.com/Helicone/ai-gateway/pull/291
> feat: better invalid config error on router update

- docker/dockerfiles/dockerfile_migrations
Ensure that the flyway migration has proper permissions
> misc: chmod the flyway on dockerfile_migrations

- web/components/templates/auth/authForm.tsx
- web/components/templates/playground/components/ModelParametersForm.tsx
- web/lib/api/db/dbExecute.ts
- web/lib/auth.ts
- web/pages/api/stripe/event_webhook/index.ts
- web/pages/signin.tsx
- web/pages/signup.tsx
Prettier format to remove errors
> misc: prettier format

- packages/prompts/types.ts
- web/components/templates/prompts2025/promptsPage.tsx
- worker/src/lib/RequestWrapper.ts
> feat: [ENG-2645] Create Prompt Button

- packages/prompts/HeliconePromptManager.ts
- sdk/python/helpers/helicone_helpers/prompt_manager.py
- sdk/python/helpers/helicone_helpers/types.py
- sdk/python/helpers/pyproject.toml
- sdk/typescript/helpers/package-lock.json
- sdk/typescript/helpers/package.json
Prompts now allows for environment control, updates to:
- Typescript SDK
- Python SDK (async and non-async)
> feat: [ENG-2674] Update Prompt SDK for environments

- supabase/migrations/20250812000000_enhanced_onboard_tracking.sql
- web/services/hooks/organizations.tsx
Adds multiple posthog events for onboarding stats:
- signup (already existed)
- onboarding
- integration
- completed quickstart
> feat: [ENG-2560] PostHog logging for Onboarding

- supabase/migrations/20250801000000_add_has_integrated_column.sql
- supabase/migrations/20250812000000_enhanced_onboard_tracking.sql
In preparation for onboarding revamp, however has some downsides. 
New signups will not have demo orgs.
> feat: Onboarding DB Changes

- web/components/layout/auth/DesktopSidebar.tsx
- web/components/layout/orgDropdown.tsx
> fix: styling for org block in sidebar

- web/components/templates/quickstart/quickstartPage.tsx
> feat: [ENG-2701] Listening for events card on quickstart

- web/components/templates/quickstart/quickstartPage.tsx
- web/components/templates/settings/providerKeySettings.tsx
- web/pages/onboarding/request/index.tsx
- web/pages/settings/providers.tsx
- adds skip button to `onboarding/request` step
- modal for adding provider keys
> feat: [ENG-2727] Onboarding QoL

- web/package.json
- web/pages/_app.tsx
- yarn.lock
This pull request introduces the React Query Devtools to the development environment of the web application, enhancing debugging capabilities for data fetching and caching. The integration is limited to development mode to avoid impacting production performance.
**Development tooling improvements:**
* Added `@tanstack/react-query-devtools` as a new dependency in `web/package.json` to enable React Query Devtools support.
* Imported `ReactQueryDevtools` from `@tanstack/react-query-devtools` in `web/pages/_app.tsx` and conditionally rendered it when `NODE_ENV` is set to "development". This provides a UI for inspecting React Query state during development. [[1]](diffhunk://#diff-ea8eb0585db40b8aa3d56b59a6d5d90ef80e5f401934dcccb8c75a7e7a6d8dd0R25) …
> feat: react query devtools in development mode

- bifrost/lib/clients/jawnTypes/public.ts
- docs/swagger.json
- valhalla/jawn/src/controllers/public/agentController.ts
- valhalla/jawn/src/tsoa-build/public/routes.ts
- valhalla/jawn/src/tsoa-build/public/swagger.json
- web/components/templates/agent/HeliconeAgentContext.tsx
- web/components/templates/agent/MessageRenderer.tsx
- web/lib/agent/tools.ts
- web/lib/clients/jawnTypes/public.ts
- **feat: add mintlify mcp to Heli**
- **fix: formatting**
> feat: add mintlify mcp to Heli

- web/components/templates/requests/RequestsPage.tsx
if a request id is specified show the drawer
> bug: [ENG-2792] request drawer not showing in direct link

- valhalla/jawn/src/lib/db/ClickhouseWrapper.ts
- web/components/layout/auth/Sidebar.tsx
This pull request updates the `Sidebar` component to conditionally display a new "HQL" navigation item based on a feature flag.
> feat: enable hql sidebar conditionally based on feature flag

- web/filterAST/toFilterNode.ts
> fix: lint for field.column

- valhalla/jawn/src/lib/db/ClickhouseWrapper.ts
- web/components/shared/notification/Notification.tsx
- web/components/shared/notification/NotificationContext.tsx
- web/components/shared/themed/themedModal.tsx
- web/components/templates/dashboard/saveFilterButton.tsx
**Notification system improvements:**
* Added a `clearNotification` method to the notification context and exposed it to consumers, allowing notifications to be programmatically cleared. The notification timeout logic now uses a ref to prevent multiple timers and ensures notifications are cleared correctly. (`web/components/shared/notification/NotificationContext.tsx` [[1]](diffhunk://#diff-cf5986e4f68184a8c4e5bd52386a970f5c6ce44df5be49f3f5b7066fbbc6ede4L1-R20) [[2]](diffhunk://#diff-cf5986e4f68184a8c4e5bd52386a970f5c6ce44df5be49f3f5b7066fbbc6ede4L32-R71)
* Updated the notification close button to use the new `clearNotification` method and hide the notification, replacing the previous placeholder alert. (`web/components/shared/notification/Notification.tsx` …
> fix: save button notifcation closeable with render optimization

- valhalla/jawn/src/controllers/public/heliconeSqlController.ts
- valhalla/jawn/src/lib/db/ClickhouseWrapper.ts
- valhalla/jawn/src/lib/errors/HqlErrors.ts
- valhalla/jawn/src/managers/HeliconeSqlManager.ts
- valhalla/jawn/src/managers/HqlQueryManager.ts
- web/components/templates/hql/HqlErrorDisplay.tsx
- web/components/templates/hql/QueryResult.tsx
- web/lib/api/hql/errorTypes.ts
This pull request introduces a comprehensive backend error handling system fo HQL, refactoring how errors are surfaced and returned from API endpoints. The changes standardize error codes, messages, and HTTP status codes, and ensure all controller methods consistently use this new error system. This improves reliability, debuggability, and frontend parsing of errors.
* Added a new module `HqlErrors.ts` defining standardized error codes (`HqlErrorCode`), error message mappings, status code mappings, and helper functions for creating and parsing errors. This module is now used throughout the HQL feature for consistent error reporting.
* All controller endpoints in `heliconeSqlController.ts` now use the new error system: errors are returned as `HqlError` objects, include error codes in …
> feat: HQL error handling

- web/components/templates/properties/propertyPanel.tsx
- web/components/templates/properties/useProperty.tsx
weren't passing in the filters to the properties query before
> bug: [ENG-2786] fix filters not working in properties page

- web/components/templates/requests/components/Chat.tsx
- web/components/templates/requests/components/ToolsRenderer.tsx
> feat: [ENG-2041] Render tools in request drawer

- valhalla/jawn/src/lib/db/test/MockClickhouseWrapper.ts
- valhalla/jawn/src/lib/db/test/TestClickhouseWrapper.test.ts
- valhalla/jawn/src/lib/db/test/clickhouseMockData.ts
- valhalla/jawn/src/lib/db/test/hqlSecurityTests.test.ts
This pull request introduces a comprehensive mock implementation for the ClickHouse client, along with a full suite of unit tests to validate its behavior. The new mock client enforces security rules, simulates row-level security, and provides realistic query responses for testing purposes. The tests cover database setup, query execution, security validation, organization context filtering, and data integrity.
> feat: testing for hql and clickhouse

- packages/__tests__/filters/toFilterNode.test.js
- packages/filters/toFilterNode.ts
- web/components/templates/dashboard/dashboardPage.tsx
- web/components/templates/dashboard/useDashboardPage.tsx
- web/components/templates/properties/propertyPanel.tsx
- web/components/templates/requests/useRequestsPageV2.tsx
- web/pages/sessions/[name]/[session_id].tsx
- web/services/hooks/sessions.tsx
- web/services/hooks/users.tsx
This pull request contains tests for the toFilterNode function
> test: toFilterNode

- web/components/templates/organization/addMemberModal.tsx
- web/pages/onboarding/members/index.tsx
- web/services/hooks/organizations.tsx
> bug: [ENG-2883] fix improper error unwrapping for add member mutation

- web/components/shared/themed/themedTimeFilterShadCN.tsx
- web/components/templates/dashboard/dashboardPage.tsx
bugs with time filter
- changing times wouldn't work or apply anything
- changing dates would be inconsistent with calendar display
- dashboard clear filter sets to 24h instead of 1 month
> bug: [ENG-2785] fix time filter to use local timezone

- .gitignore
- valhalla/jawn/scripts/README.md
- valhalla/jawn/scripts/seed-clickhouse.ts
Script to seed the ClickHouse database with test data
> feat: load clickhouse rows for local testing

- valhalla/jawn/src/lib/clients/constant.ts
- valhalla/jawn/src/managers/InAppThreadsManager.ts
- valhalla/jawn/src/services/SlackService.ts
- web/components/templates/agent/ChatInterface.tsx
- web/components/templates/agent/MessageRenderer.tsx
- web/components/templates/requests/components/chatComponent/single/images/ImageModal.tsx
- web/lib/agent/tools.ts
- yarn.lock
We will need to create a user token in the slack app with the `file:create` scope
> feat: image support on helix

- packages/prompts/types.ts
> feat: [ENG-3129] support cache control in HeliconeChatCreateParams

- packages/__tests__/cost/__snapshots__/registrySnapshots.test.ts.snap
- packages/cost/models/authors/openai/oss/endpoints.ts
- worker/test/ai-gateway/registry-openai.spec.ts
- Add gpt-oss for deepinfra
- Tests & snapshots
> feat: integrate gpt-oss/deepinfra to gateway

- packages/__tests__/cost/__snapshots__/registrySnapshots.test.ts.snap
- packages/__tests__/cost/registrySnapshots.test.ts
- packages/cost/models/authors/anthropic/claude-3.5-haiku/endpoints.ts
- packages/cost/models/authors/anthropic/claude-3.5-sonnet-v2/endpoints.ts
- packages/cost/models/authors/anthropic/claude-3.7-sonnet/endpoints.ts
- packages/cost/models/authors/anthropic/claude-4.5-sonnet/endpoints.ts
- packages/cost/models/authors/anthropic/claude-opus-4-1/endpoints.ts
- packages/cost/models/authors/anthropic/claude-opus-4/endpoints.ts
- packages/cost/models/authors/anthropic/claude-sonnet-4/endpoints.ts
- packages/cost/usage/getUsageProcessor.ts
also added usage processors for deepinfra and novita
> test: [ENG-3238] check if ptb enabled endpoints have usage processors

- packages/__tests__/cost/__snapshots__/registrySnapshots.test.ts.snap
- packages/cost/models/authors/meta/llama/endpoints.ts
- worker/test/ai-gateway/registry-meta-llama.spec.ts
Integrate novita/llama-4-scout model into AI gateway
> integrate novita/llama-4-maverick

- packages/__tests__/cost/__snapshots__/registrySnapshots.test.ts.snap
- packages/cost/models/authors/deepseek/deepseek-reasoner/model.ts
- packages/cost/models/authors/deepseek/r1-distill/endpoints.ts
- worker/test/ai-gateway/registry-deepseek.spec.ts
Integrate deepinfra/deepseek-r1-llama-distilled-70b
> integrate deepinfra/deepseek-r1-llama-distilled-70b

- packages/__tests__/cost/__snapshots__/registrySnapshots.test.ts.snap
- packages/cost/models/authors/alibaba/qwen/endpoints.ts
- packages/cost/models/authors/alibaba/qwen/models.ts
- worker/test/ai-gateway/registry-alibaba.spec.ts
Integrate Qwen3-235b-a22b-thinking with DeepInfra provider
> integrate deepinfra/qwen3-235-a22b-thinking

- packages/__tests__/cost/__snapshots__/registrySnapshots.test.ts.snap
- packages/cost/models/authors/meta/llama/endpoints.ts
- worker/test/ai-gateway/registry-meta-llama.spec.ts
Add functions parameter to Llama 4 Scout
> include functions for novita/llama-4-scout

- packages/__tests__/cost/__snapshots__/registrySnapshots.test.ts.snap
- packages/cost/models/authors/moonshotai/kimi-k2/endpoints.ts
- packages/cost/models/authors/moonshotai/kimi-k2/models.ts
- worker/test/ai-gateway/registry-moonshot-spec.ts
Integrate kimi-k2-instruct model with novita provider
> Integrate novita/kimi-k2-instruct

- packages/cost/models/authors/alibaba/qwen/endpoints.ts
- packages/cost/models/authors/deepseek/deepseek-reasoner/endpoints.ts
- packages/cost/models/authors/deepseek/deepseek-v3/endpoints.ts
- packages/cost/models/authors/google/gemma-3/endpoints.ts
- packages/cost/models/authors/meta/llama/endpoints.ts
- packages/cost/models/authors/mistralai/mistral-nemo/endpoints.ts
Added quantization parameter to models that were missing it
> Added quantization to oss models
