Helicone/helicone

web/pages/api/hello.ts
worker/src/cache.ts
worker/src/index.ts
worker/wrangler.toml

Migrated the response body to fork so that we can in parallel log the response at the same time that it is being sent back to the user. 
Look for this code: 
```typescript
const [readable, readableLog] = response.body?.tee()
```
This is where it all changes.
The current preview branch is now using `https://preview-oai.hconeai.com/v1/chat/completions`
You can test this endpoint with this piece of code (I just threw it in an endpoint and tested it)
```typescript
var es = await fetch("http://127.0.0.1:8787/v1/engines/davinci/completions", {
headers: {
"Content-Type": "application/json",
Authorization: "Bearer " + "<API KEY>",
},
method: "POST",
body: JSON.stringify({
prompt: "HELLO write me a book",
temperature: 0.75,
top_p: 0.95,
max_tokens: 10,
stream: true,
stop: ["\n\n"],
}),
});
const …
```

Streaming support

---

web/components/templates/requests/requestsPage.tsx
web/components/templates/requests/useRequestsPage.tsx
web/lib/api/graphql/query/heliconeRequest.ts
web/lib/api/request/request.ts
web/services/hooks/requests.tsx
web/services/lib/filters/frontendFilterDefs.ts

This increases speed and fixes the bug where if users had multiple users log with API keys it would show up twice.

Remove columns from get requests

---

docs/mint.json

It is currently linking to an old repo

fix link to repo

---

web/components/templates/home/codeSnippet.tsx

Update the code snippet in Helicone's Onboarding to reflect openai's npm package v4 configuration from v3.
https://github.com/openai/openai-node/discussions/217
Prev:

Update TS openai code sample to v4

---

docs/getting-started/integration-method/anthropic.mdx
web/lib/api/metrics/costCalc.ts
web/lib/sql/constants.ts
worker/src/lib/limits/check.ts

This PR will add claude pricing to wherever file I found have anything related to cost. This should close #909. I've also fix some docs problem related to integrating Helicone with Anthropic client in both Python and Node (TS), this should close #883.
If any of my implementation is not up to your standard, or need something to change please let me know!
p.s. I think you can change your `getTokenCount` function in worker folder to use [anthropic typescript tokenizer](https://github.com/anthropics/anthropic-tokenizer-typescript) instead of running it with Python on another instances.

Add claude pricing & fix anthropic docs

---

docs/features/jobs/quick-start.mdx

For images, syntax for images include a `/` before the relative path. For example, 
```
```
instead of 
```
```

Change image syntax

---

worker/package.json
worker/src/lib/dbLogger/tokenCounter.ts
worker/yarn.lock

This PR will add anthropic tokenizer to worker, such that it does not need another service running just to tokenize anthropic models.
As always if there's any question, or changes I need to make, please do tell me!
p.s. Seems like wrangler now supports WASM, and that could (maybe) make the perf slightly better? [tiktoken npm library already supports it](https://github.com/dqbd/tiktoken#cloudflare-workers)

Add anthropic tokenizer in worker

---

docs/getting-started/integration-method/azure.mdx

Helicone seems to be adding the `/chat/completions` part automatically.  Request is failing if we include it in the URL.

Fix Azure baseURL field in docs

---

docs/features/advanced-usage/caching.mdx
docs/features/advanced-usage/custom-properties.mdx
docs/features/advanced-usage/custom-rate-limits.mdx
docs/features/advanced-usage/omit-logs.mdx
docs/features/advanced-usage/retries.mdx
docs/features/advanced-usage/user-metrics.mdx
docs/getting-started/integration-method/gateway.mdx
docs/getting-started/integration-method/openai-proxy.mdx
docs/helicone-headers/intro.mdx
web/components/templates/home/codeSnippet.tsx

Langchain has deprecated the baseOptions, so I have updated the documentation to reflect this change.
```ts
/** @deprecated Use defaultHeaders and defaultQuery instead */
baseOptions?: {
headers?: Record<string, string>;
params?: Record<string, string>;
};
```

Docs: Fixed typescript config for Langchain

---

worker/src/db/DBWrapper.ts
worker/src/lib/RequestWrapper.ts
worker/src/lib/secureCache.ts
worker/wrangler.toml

I created a function that allows us to easily wrap any call with our secure cache so that we can secure store stuff in cache quickly without a lot of code
```ts
export async function getAndStoreInCache<T, K>(
key: string,
env: SecureCacheEnv,
fn: () => Promise<Result<T, K>>
): Promise<Result<T, K>> {
const cached = await getFromCache(key, env);
if (cached !== null) {
return ok(JSON.parse(cached) as T);
}
const value = await fn();
if (value.error !== null) {
return value;
}
await storeInCache(key, JSON.stringify(value.data), env);
return value;
}
```
to use it just do this 
```ts
const { data, error } = await getAndStoreInCache(
`getProviderKeyFromProxy-${authKey}`,
env,
async () => await this.getProviderKeyFromProxy(authKey, env)
);
```
This will execute the function passed in and if it …

cleaned up cache code

---

web/components/templates/auth/authForm.tsx
web/pages/signin.tsx
web/pages/signup.tsx

Connect GitHub auth as a secondary auth options.
- Create a GitHub OAuth in Helicone Org
- Activate it on Supabase
- Edit login page and add Github Auth button 
- End-To-End test it

Add Github authentication support

---

docs/getting-started/integration-method/openai.mdx

We don't support curly brackets well and may cause the page to go down. Before we put in a fix, we suggest to escape either with backticks or `/`

fix curly brackets

---

web/components/templates/playground/playgroundPage.tsx

Hey!
Was playing with your playground page and could not find vision and new turbo models in the models dropdown.
This PR will add the models.

Add preview models to the Playground page

---

valhalla/packages/helicone-shared-ts/src/db/valhalla.ts
valhalla/packages/jawn/src/index.ts

We had a huge spike in requests. Which caused our node to fail
So I am adding more requests... I am also going to make the min number of nodes 2, and making sure our health check actually checks the db

download more ram

---

clickhouse/migrations/schema_15_update_order_by_properties.sql
web/lib/api/properties/propertyParams.ts

This is a quick fix that is faster...
The real fix is to get rid of  `properties_copy_v2`
and replace it with 
```sql
CREATE TABLE IF NOT EXISTS default.properties_v3
(
`id` Int64,
`created_at` DateTime64,
`request_id` UUID,
`key` String,
`value` String,
`organization_id` UUID,
)
ENGINE = MergeTree
PRIMARY KEY (organization_id, key, value, id)
ORDER BY (organization_id, key, value);
```
This was before we knew how to properly use clickhouse...

Property Value Speed Improvements - move property value query to response_with_property table

---

costs/src/providers/anthropic/index.ts
web/packages/cost/providers/anthropic/index.ts
worker/src/packages/cost/providers/anthropic/index.ts

This PR adds the pricings for both the sonnet and haiku models from anthropic.

add anthropic sonnet and haiku pricing

---

docs/swagger.json
valhalla/jawn/src/controllers/public/experimentController.ts
valhalla/jawn/src/controllers/public/experimentDatasetController.ts
valhalla/jawn/src/controllers/public/promptController.ts
valhalla/jawn/src/controllers/public/requestController.ts
valhalla/jawn/src/lib/shared/filters/filterDefs.ts
valhalla/jawn/src/tsoa-build/public/routes.ts
valhalla/jawn/src/tsoa-build/public/swagger.json
web/lib/clients/jawnTypes/public.ts
web/services/hooks/requests.tsx

One of the annoying things about `FilterNode` is that there was no way to isolate what filters a specific endpoint had access to. Now it is possible to isolate exactly what an endpoint can filter by...
Here is the new request's endpoint limited to just request, response and feedback
In the docs they are no longer inundated with a bunch filters that would fail (some users were trying to filter by tables and getting errors)

More precise FilterNode object

---

web/components/templates/requestsV2/requestRow.tsx
web/services/lib/requests.ts

Add scores on request page

---

docs/getting-started/integration-method/hyperbolic.mdx
docs/getting-started/quick-start.mdx

- Changed "You can seamlessly integrate Helicone **with your** OpenAI compatible models that are deployed on Hyperbolic." to "You can seamlessly integrate Helicone **with the** OpenAI compatible models that are deployed on Hyperbolic."
- since they haven't enabled users to deploy their own models yet

Hyperbolic

---

valhalla/dockerfile_eu
valhalla/jawn/src/lib/tokens/tokenCounter.ts

remove token counting on stream in favor of https://docs.helicone.ai/use-cases/enable-stream-usage\#correct-cost-calculation-while-streaming

Token counting for stream on OpenAI removed because it was causing lag

---

bifrost/components/layout/navbar.tsx

added direct access to the open stats page

---

valhalla/jawn/src/lib/handlers/HandlerContext.ts
valhalla/jawn/src/lib/handlers/LytixHandler.ts
valhalla/jawn/src/tsoa-build/private/routes.ts
valhalla/jawn/src/tsoa-build/private/swagger.json
web/lib/clients/jawnTypes/private.ts
worker/src/lib/clients/KafkaProducer.ts
worker/src/lib/dbLogger/DBLoggable.ts
worker/src/lib/models/HeliconeHeaders.ts

We (Lytix) have just provisioned some EU servers and we have someone who would like to use us via Helicone. They want to remain GDPR compliant so we have provisioned some EU servers and would like to push metrics directly to that server.
See the original PR that added lytix [here](https://github.com/Helicone/helicone/pull/2157)

Add Optional Lytix Host Header

---

valhalla/jawn/src/managers/request/RequestManager.ts

Sometimes when we make a change in clickhouse via feedback or cutom properties. There might be multiple requests before Clickhouse performs a merge. To combat this, here is a small hack to fix this

filter out duplicates in clickhouse

---

helicone-node/async_logger/HeliconeAsyncLogger.ts

example usage:
```ts
import { HeliconeAsyncLogger } from "@helicone/helicone";
import { OpenAI } from "openai";
const logger = new HeliconeAsyncLogger({
apiKey: process.env.HELICONE_API_KEY
providers: {
openAI: OpenAI
}
});
logger.init();
const openai = new OpenAI();
const headers = {
"Helicone-Property-Client": "helicone-sdk"
};
logger.withProperties(
headers,
async () => {
const completion = await openai.chat.completions.create({
messages: [
{"role": "system", "content": "You are a helpful assistant."},
{"role": "user", "content": "How would a multi-galactiy civilization do things?"}
],
model: "gpt-4o-mini",
max_tokens: 50
}, {
headers: headers
});
}
);
```

feat: add support for providing metadata via node sdk≤

---

web/components/templates/organization/plan/proBillingPage.tsx

When clicking on cancel, the switch should go back to the default stage like so:
https://github.com/user-attachments/assets/2fcddfb2-cb4b-47ce-b9da-a6070ecc8770
Before:
https://github.com/user-attachments/assets/c4a493ca-972d-4472-adc8-505291f89b2c

billing page pro plan, switch alerts toggle fix

---

web/components/templates/dashboard/dashboardPage.tsx
web/components/templates/settings/reportsPage.tsx
web/components/templates/settings/settingsLayout.tsx
web/pages/settings/reports.tsx

https://github.com/user-attachments/assets/683dbb41-a462-4911-b16e-a7122cac4172

move reports from dashboard to settings

---

valhalla/jawn/genTypes.py
valhalla/jawn/nodemon.json
valhalla/jawn/package.json
valhalla/jawn/src/lib/db/supabase.ts
valhalla/jawn/tsconfig.json
valhalla/jawn/yarn.lock

- run ts-node and genTypes concurrently (https://tsoa-community.github.io/docs/live-reloading.html#adding-a-dev-script)
- this just means that we dont wait for genTypes to finish before we run ts-node (it is not dependant on that)
- move to swc (the time change here at first was very much but the time difference is actually very random really, sometimes around 11-12, sometimes around 20, sometimes 5) — so not waiting for this to finish (in step 1) is a pretty significant improvement
- run openapi typescript gen in parallel (these were barely taking much time anyways, but this does speed it up by a very small margin)

Speed up Jawn Dev Server

---

web/package.json
web/styles/globals.css
web/tailwind.config.js
web/yarn.lock

Upgrade assistant-ui packages to:
- support dark mode
- fix bugs around adding assistant messages / changing message roles
- fix turbopack support (removes need for global.css import workaround)
- fixed a few border colors

feat: playground dark mode support

---

bifrost/lib/clients/jawnTypes/private.ts
bifrost/lib/clients/jawnTypes/public.ts
docs/swagger.json
valhalla/jawn/src/controllers/public/evaluatorController.ts
valhalla/jawn/src/tsoa-build/private/routes.ts
valhalla/jawn/src/tsoa-build/private/swagger.json
valhalla/jawn/src/tsoa-build/public/routes.ts
valhalla/jawn/src/tsoa-build/public/swagger.json
web/lib/clients/jawnTypes/private.ts
web/lib/clients/jawnTypes/public.ts

the same type was being using in multiple areas...see this Gemini response::: 
<html><head></head><body><div><div jsname="OsZLCd" data-mrc="GAE" class="yf" data-async-fc="EqEBCmJBSkc5SmtPZjl1cjNhc3YxUlhYMVVsOXl2OEl2aWd1Tl92aktGVkFfU0hZOGxoZWl2VGVpWHJ0RmJEa2FpVXpoYjQyMFJwb3ZMNExfd2sxOFIzc0h1ekpnek1fMlZXTm9xdxIXX3NzM1o4U29NLXJRa1BJUG05Ym9xUTQaIkFGWHJFY293Mmg0cmtCdWtqdVVPb2E3VzlvdnNqR1lDMlE" data-async-fcv="3" data-async-ons="7159" id="fc__ss3Z8SoM-rQkPIPm9boqQ4_1" eid="sMw3Z4K3L5690PEP2IWJoQ4"><div jsname="OsZLCd" data-mdv="0" data-mrc="GAE" class="yp" data-async-fc="EqEBCmJBSkc5SmtQX3B0LVNwOXh1UjB1c2Q5NUdYWlR5VEZTNmc3NWh5M3BydVZwdTdpNkUwRVM1RUxnWmt3X0JvZDZRWU1SREFQU1NMZUE1WThnV3g2WV9WSHFvUnU2Q2J0a18tdxIXc013M1o0SzNMNTY5MFBFUDJJV0pvUTQaIkFGWHJFY3JSMDRpQ25ZZ3ExZ2F6YVZ2cnJwcTBpa2x2T1E" …

Fix Jawn type generation

---

docs/getting-started/self-host/docker.mdx

The previous add user flow doesnt work
Fix in the doc Includes:
1. Correcting the port in the docs (8989) to the host port for the studio (54323)
2. Letting user know to update env variable `ENABLE_EMAIL_AUTOCONFIRM` to `true` - to let auth work locally
Related : #2977

Update studio port to the one mentioned in the compose.yml

---

README.md

This link is broken clicking on Github repository.  Adding https:// like the other links.
Reported: https://github.com/Helicone/helicone/issues/3093

fix: signup link

---

web/components/templates/prompts/promptsPage.tsx

The padding on the left is fixed. Used ISLAND_MARGIN like the above component.

Small change: Prompt cards required padding

---

supabase/config.toml

Found when going through [https://docs.helicone.ai/getting-started/self-host/manual](https://docs.helicone.ai/getting-started/self-host/manual) with a modern Supabase CLI version.

Fix: Specifies localhost schema as "public" in supabase/config.toml

---

bifrost/app/components/Layout.tsx
bifrost/app/page.tsx
bifrost/components/home/Banner.tsx

[merge on launch day] added banner for HN launch

---

web/components/ui/button.tsx

We're not using font-size 16px almost anywhere so the button was looking off in a lot of places

Revert button style

---

clickhouse/ch_hcone.py
docker/docker-compose.yml
docker/dockerfiles/dockerfile_clickhouse_migration_runner
valhalla/dockerfile
valhalla/jawn/src/lib/handlers/OnlineEvalHandler.ts

1. Fix `jawn` build
2. fixed clickhouse migration runner to work without a password
3. Added docs around worker issues and pushing users to use jawn as proxy
```
git clone git@github.com:Helicone/helicone.git
cd helicone
git checkout docker-compose-working
cd docker 
cp .env.example .env
docker compose up
```
make an account by doing to `localhost:54324`
sign in and make an API key
then make a request
```
from openai import OpenAI
import os
from dotenv import load_dotenv
load_dotenv()
SESSION_ID = "test-session-id-4"
openai_client = OpenAI(
api_key=os.getenv("OPENAI_API_KEY"),
base_url="http://127.0.0.1:8585/v1/gateway/oai/v1",
default_headers={
"Helicone-Auth": f"Bearer ...",
"Helicone-Session-Id": SESSION_ID,
}
)
response = openai_client.completions.create( …
```

getting docker in a much better state, works out of the box

---

web/components/layout/auth/Sidebar.tsx
web/components/shared/prompts/AutoImprove.tsx
web/components/shared/prompts/EvalsPanel.tsx
web/components/shared/prompts/MessagesPanel.tsx
web/components/shared/prompts/PromptBox.tsx
web/components/shared/prompts/VariablesPanel.tsx
web/components/shared/prompts/helpers.ts
web/components/shared/universal/Popup.tsx
web/components/shared/universal/VersionSelector.tsx
web/components/templates/prompts/id/promptIdPage.tsx
web/lib/api/llm/generate-stream.ts
web/lib/api/llm/generate.ts
web/pages/api/llm/index.ts
web/prompts/auto-improve.ts
web/prompts/perform-edit.ts
web/types/prompt-state.ts
web/utils/messages.ts
web/utils/variables.ts

- New: Auto-improve feature
- Update: Added support for streaming .reasoning from a message
- Misc: Variable changes no longer cause a dirty state
- Misc: Other ui tweaks
- Refactor: Variable state data type
- WIP (paused): Prompt evals panel

New: Auto-Improve prompts feature + other tweaks

---

sdk/typescript/async/.gitignore
sdk/typescript/async/README.md
sdk/typescript/async/async_logger/HeliconeAsyncLogger.ts
sdk/typescript/async/package-lock.json
sdk/typescript/async/package.json

> ⚠️ **BLOCKED**: This PR is blocked pending the merge of [openllmetry-js#545](https://github.com/traceloop/openllmetry-js/pull/545) which adds core TogetherAI instrumentation support.
Adds native TogetherAI support to enable monitoring and analyzing TogetherAI API usage with Helicone's observability features.
- Added TogetherAI integration (`together-ai ^0.13.0`) 
- Extended logger and interfaces for TogetherAI support
- Bumped to v1.0.1
- Updated dependencies including `@traceloop/node-server-sdk@0.12.1`
```typescript
import Together from "together-ai";
import { HeliconeAsyncLogger } from "@helicone/async";
export function createTogetherClient({ task }: { task?: string } = {}) {
const logger = new HeliconeAsyncLogger({
apiKey: process.env.HELICONE_API_KEY!,
headers: { …
```

TogetherAI SDK support Helicone Async

---

packages/llm-mapper/types.ts
packages/llm-mapper/utils/getMappedContent.ts
valhalla/jawn/src/lib/handlers/LoggingHandler.ts
valhalla/jawn/src/packages/llm-mapper/types.ts
valhalla/jawn/src/packages/llm-mapper/utils/getMappedContent.ts
web/packages/llm-mapper/types.ts
web/packages/llm-mapper/utils/getMappedContent.ts

Adds functions to generate complete text previews of LLM requests/responses, replacing 30-char truncated previews.
```ts
// Before: Limited 30-char previews
preview: {
request: mappedContent.preview.request?.slice(0, 30),
response: mappedContent.preview.response?.slice(0, 30),
}
// After: Full text with size limits
preview: {
fullRequestText: () => messagesToText(request.messages).slice(0, MAX_CONTENT_LENGTH),
fullResponseText: () => messagesToText(response.messages).slice(0, MAX_RESPONSE_LENGTH)
}
```
Key changes:
- Added `fullRequestText()` and `fullResponseText()` to `LLMPreview` type
- Implemented message concatenation with all components (content, tool calls, roles)
- Added size limits (2MB request, 100KB response) to prevent memory issues
- Fixed type errors in preview generation …

improve text extract for search

---

sdk/python/async/helicone_async/async_logger.py

Due to the way OpenLLMetry is checking for "tracing enabled" or not in the set_association_properties function, the traceloop content enable/disable has to be using the global env variable. This should be fine since we were setting it to false globally before anyways.
OpenLLMetry code reference:
https://github.com/traceloop/openllmetry/blob/4c59eb3f13eaa16346965602fc893f4e00a4c98b/packages/traceloop-sdk/traceloop/sdk/tracing/tracing.py#L166-L174
https://github.com/traceloop/openllmetry/blob/4c59eb3f13eaa16346965602fc893f4e00a4c98b/packages/traceloop-sdk/traceloop/sdk/config/__init__.py#L12-L13
The `__content_allow_list` cannot be changed because it is automatically loading the `associationPropertyAllowList` which is only available if using traceloop's dashboard

fix association properties not showing request data on async logger

---

docs/getting-started/integration-method/gateway.mdx

Based on my usage of the Platform, Google apis are supported, including the Cost support. I'm not sure about the Dedicated domain part though.
The columns seem broken in raw markdown but they should be displayed fine when rendered by a markdown table component. I haven't tested the display part manually but I can do it if needed.

Add Google to the list of Approved Domains in the docs

---

bifrost/app/changelog/changes/20250124-prompt-editor/metadata.json
bifrost/app/changelog/changes/20250124-prompt-editor/src.mdx
bifrost/tsconfig.json

Elevate your prompt development with our new best-in-the-world editor, designed for peak efficiency and creativity. **Now Live for all Prompts & Experiments users!**
[demo video]
- **Advanced Text Editors**
- Intelligent auto-complete
- Magic Toolbar with powerful shortcuts
- `⌘ E`: Quickly add variables
- `⌘ J`: Insert XML delimiters
- `⌘ K`: Perform instant edits
- **Workflow Optimization**
- Side-by-side prompt-response view
- Instant Save & Run for real-time feedback
- **Version Management** 
- Fast version switching
- One-click version promotion
- Simple deployment via prompt ID
- **Data & Model Support**
- Import variables from live production data
- Quickly link to an experiment
- Message pairs and prefill support
- Full compatibility with leading AI models:
- Anthropic
- OpenAI
- …

Changelog: Helicone Prompt Editor

---

docs/getting-started/self-host/manual.mdx
web/package.json
web/yarn.lock

- Updates the [setup instructions](https://docs.helicone.ai/getting-started/self-host/manual) to avoid the following error:
```
Error: Failed to load external module react-lottie: ReferenceError: document is not defined
```
As seen in the screenshot:
If not using the correct version of Node. Also set the `engines` property in the `package.json` to reflect this required version

Fix: Update Docs and min node version in package.json

---

valhalla/jawn/src/managers/evaluator/EvaluatorManager.ts

Fixes an issue in how the range labels were being calculated. The original query had:
- ceil(bucket * 20) for the end of the range
- floor(bucket * 20) for the start of the range
When bucket = 0 (for scores 0-19), both of these would evaluate to 0, resulting in a range of "0-0".
The fix changes this to bucket * 20 for the start of the range, and (bucket + 1) * 20 for the end of the range.
This creates proper bucket ranges like "0-20", "20-40", etc.

fix: Evaluator stats distribution query

---

worker/src/lib/clients/KVRateLimiterClient.ts
worker/src/lib/managers/AlertManager.ts
worker/src/lib/managers/LoopsManager.ts
worker/src/lib/managers/UsageLimitManager.ts.ts
worker/src/lib/safePut.ts
worker/src/lib/util/cache/cacheFunctions.ts
worker/src/lib/util/cache/secureCache.ts
worker/src/routers/gatewayRouter.ts

In rare cases the KV put will cause the current process to crash if users have cache enabled or rate limits enabled. 
We are replacing all our puts to wrap them in `safePut` which does and exponential backoff when writing cache keys

hotfix: making exponential backoff for KV store

---

valhalla/jawn/src/lib/handlers/LoggingHandler.ts

We are getting into some situations where the template (for some reason) is the messages array and ends up looking something like 
`['<helicone-auto-prompt-input idx=0 />', '<helicone-auto-prompt-input idx=1 />', '<helicone-auto-prompt-input idx=2 />']`
Where the input variables are like this
```json
{role: 'user', content: "What's the weather SF\n\n", id: 0}
```
U think we should just throw this as an unhandled template type since it should be in a JSONB as 
```json
{
"messages": ['<helicone-auto-prompt-input idx=0 />', '<helicone-auto-prompt-input idx=1 />', '<helicone-auto-prompt-input idx=2 />']
}
```

hotfix: invalid prompt template

---

bifrost/packages/llm-mapper/mappers/openai/realtime.ts
examples/qawolf-ws/index.ts
packages/llm-mapper/mappers/openai/realtime.ts
valhalla/jawn/src/lib/proxy/WebSocketProxyRequestHandler.ts
valhalla/jawn/src/packages/llm-mapper/mappers/openai/realtime.ts
web/packages/llm-mapper/mappers/openai/realtime.ts
worker/src/packages/llm-mapper/mappers/openai/realtime.ts

Misc: Add simulated reproduction to examples
Fix: Only use parse in mapper if isJson
Fix: Now also using safeJsonStringify

Fix: Unsafe realtime llm-mapper parse

---

packages/cost/providers/openai/index.ts

Adds the GPT-4.1 family to Openai Costs and model details
See https://openai.com/index/gpt-4-1/ for announcement

Add gpt 4.1 family to costs

---

docs/getting-started/integration-method/manual-logger-typescript.mdx
docs/guides/cookbooks/manual-logger-streaming.mdx
sdk/typescript/helpers/manual_logger/HeliconeManualLogger.ts
sdk/typescript/helpers/package.json

Enhance logSingleRequest with latency tracking
Before:
```ts
await helicone.logSingleRequest(requestBody, JSON.stringify(response), { "Helicone-User-Id": userId });
```
After:
```ts
await helicone.logSingleRequest(requestBody, JSON.stringify(response), {
additionalHeaders: { "Helicone-User-Id": userId },
latencyMs: 1000 // Optional custom latency tracking
});
```

latency as extra arg and moving headers to options

---

docs/integrations/openai/responses.mdx
docs/mint.json

Generate documentation for the OpenAI Responses API.
- Include the Responses API inside OpenAI's the sidebar
- Generate documentation leveraging OpenAI examples

Include OpenAI Responses API to docs

---

bifrost/components/blog/HeadingWithCopyLink.tsx
bifrost/mdx-components.tsx

**A small UX improvement:** 
- hover to copy link to heading 
- click to copy + jump to heading 
**why?** 
- now you can reference a specific section of our blog, rather than linking the entire blog
- help us acquire more backlinks
- more precise linking internally
behaviour matches [this company](https://incident.io/building-with-ai/built-our-own-ai-tooling#introducing-workbench) and [Mintlify's](https://docs.helicone.ai/features/sessions).

Added "copy" function to blog headings

---

web/components/templates/requests/components/chatComponent/single/JsonRenderer.tsx

Modifies JsonRenderer:
- if is a string (level 0), then show without quotes and account for newlines
- if json and rendering strings past lvl0, show with quotes and show literal newlines

[ENG-1575] Account for newlines in tool output renderer for strings

---

web/components/layout/SidebarHelpDropdown.tsx
web/components/layout/orgDropdown.tsx
web/package.json
web/yarn.lock

- intercom workflow https://app.intercom.com/a/apps/mna0ba2h/automation/workflows/47987208?mode=edit&visual=enabled
- 
- only show intercom on dashboard (will not show on other pages)
- notifies slack but doesn't support slack integration. Can just use one account
Free trails ends in 14 days
notion - https://www.notion.so/helicone/Intercom-1edc78c0f25e809f8881f1630b17f71f?pvs=4

[ENG-1561] Add Intercom Support in Replace of Pylon and Messages with Slack

---

web/services/hooks/requests.tsx

`processFilter` used on the `request/count` call in the requests page improperly handles numbers and non-dates on comparisons that are not eq or neq.

[ENG-1619] Fix improperly parsed filters

---

web/components/templates/requests/RenderHeliconeRequest.tsx
web/components/templates/requests/RequestDrawer.tsx
web/components/templates/requests/components/Realtime.tsx
web/components/templates/sessions/sessionId/Tree/TreeView.tsx

before:
1. split realtime request into a bunch of requests for each turn/action in the session
2. rendered mode shows the current turn
instead:
2. rendered mode shows full conversation, but scrolls to the current message and makes others grayed out

[ENG-1631] Show full conversation in rendered mode

---

bifrost/next.config.mjs

- `/community` page now redirects to `/customers` page

added redirect for community page

---

docs/integrations/openai/javascript.mdx
docs/integrations/openai/python.mdx

Included tutorial videos for OpenAI docs for JS & Python.

Include videos in OpenAI docs

---

docs/getting-started/self-host/docker.mdx
docs/getting-started/self-host/kubernetes.mdx

This pull request updates the self-hosting documentation for deploying Helicone using Docker Compose and Kubernetes/Helm. It introduces updated setup instructions and prerequisites for installing Helicone without Supabase.

docs: [ENG-1642] Updated docs for Docker Compose and Kubernetes to be up to date

---

docker/terraform/main.tf

This pull request adds a new AWS ECR repository resource for the `helicone` service in the Terraform configuration. The most important change is the creation of this repository with specific configurations.
* Added a new `aws_ecr_repository` resource named `helicone` in `docker/terraform/main.tf`. This repository is configured with mutable image tags and enables image scanning on push.

misc: Add ECR repository for helicone

---

packages/cost/providers/google/index.ts

https://ai.google.dev/gemini-api/docs/pricing#gemini-2.5-flash
Release: https://blog.google/products/gemini/gemini-2-5-model-family-expands/
This is different from gemini-2.5-flash-preview

Add gemini-2.5-flash pricing

---

supabase/migrations/20250716011118_request_gateway_router_id.sql
supabase/migrations/20250718011118_request_gateway_drop_router_id.sql

This commit deletes the SQL migration files related to the `gateway_router_id` and `gateway_deployment_target` columns in the `request` table, as they are no longer needed.

chore: remove deprecated request gateway router ID migration files

---

valhalla/jawn/src/lib/handlers/PostHogHandler.ts
worker/src/lib/clients/PosthogClient.ts

**Problem:**
When integrating PostHog analytics, Helicone was always sending a random UUID as the `distinct_id` for each event, instead of using the actual user identifier (`Helicone-User-Id`).
**Impact:**
This caused PostHog to create a new "person" for every event.
- PostHog’s `distinct_id` is the primary way to group events by user.
- If a random UUID is used for every event, PostHog cannot associate events with the same user, breaking all user-level analytics.
- The correct behavior is to use a stable, user-specific identifier (like `Helicone-User-Id`) as the `distinct_id`.
1. **Sent a test request with a fixed `Helicone-User-Id`:**
```
curl https://oai.hconeai.com/v1/chat/completions \
-H "Authorization: Bearer sk-...REDACTED..." \
-H "Helicone-Auth: Bearer sk-...REDACTED..." \
-H …
```

fix: Use Helicone-User-Id as PostHog distinct_id instead of random UUID

---

clickhouse/ch_hcone.py
docker/dockerfiles/dockerfile_migrations

This pull request introduces enhancements to the ClickHouse password handling in `ch_hcone.py` and updates the migration process in the Dockerfile for improved reliability. The most important changes include adding a command-line option for specifying the ClickHouse password, improving the fallback logic for password retrieval, and adding a repair step to the migration process.
* Added a `--password` command-line argument to allow users to specify the ClickHouse server password directly. (`clickhouse/ch_hcone.py`, [clickhouse/ch_hcone.pyR187-R189](diffhunk://#diff-e51c85794840d19ed7355d816dcb709118e4c24758addff757cfefe01abdf704R187-R189))
* Updated the password retrieval logic to prioritize the command-line argument over the `CLICKHOUSE_PASSWORD` environment variable, ensuring more …

fix: Enable flyway repair and password to ch_hcone.py for clickhouse

---

web/components/templates/gateway/gatewayPage.tsx
web/components/ui/drawer.tsx
web/components/ui/label.tsx
web/styles/globals.css

- the label component wasn't visible on dark mode - changed it to use the text-muted-foreground class instead of using manual color classes
- changed the drawer to not use slate color and use bg-background to appear less blue which looked off with our ui
- improved visibility of the badge which says no provider keys
- added components with the hsl colors on the global.css file so that color related extensions can pick that up on show a preview

chore: improve dark mode on gateway pages and label component

---

sdk/typescript/helpers/.npmignore
sdk/typescript/helpers/package-lock.json
sdk/typescript/helpers/package.json
sdk/typescript/helpers/tsup.config.ts

- Helpers SDK uses @helicone-package which doesn't exist
- Fixes build to use tsup to properly bundle in the templating code
- Add openai as a peer dependency to prevent conflicts
- Build no longer includes raw source files, only `dist`

feat: Fix Typescript Helpers SDK build

---

worker/src/lib/db/APIKeysStore.ts
worker/src/lib/managers/APIKeysManager.ts
worker/src/lib/managers/ProviderKeysManager.ts
worker/src/lib/util/cache/secureCache.ts
worker/src/routers/api/apiRouter.ts

- This PR adds the ability to track removal of keys. (If a user deletes an API key, it should stop working)
- This PR also optimizing how we store keys. We are only ever looking within the last day of both updated and created keys to load into our cache. We call these periodically every 5 minutes and we execute it as well whenever it changes on the frontend. This reducing the overhead the worker needs to do and drastically reduces the number of KV puts and gets. This is okay, because for older keys we will store it into the cache if we cannot find it on the first call. So the first call will be slow but subsequent calls will be faster.

optimize caching keys

---

docker/dockerfiles/dockerfile_web

This pull request refactors the `docker/dockerfiles/dockerfile_web` build process to use a multi-stage Docker build. The changes aim to optimize dependency installation, improve build efficiency, and keep the final image smaller and more secure.
**Docker build process improvements:**
* Refactored the Dockerfile to use a multi-stage build, separating the build environment (`builder`) from the final runtime image for better efficiency and security.
* Moved the `yarn install` step to the builder stage and included only the necessary files in the final image, reducing image size and potential attack surface.
* Added explicit copying of `package.json` files from various package directories before installing dependencies, ensuring all workspace dependencies are correctly resolved during the …

fix: frozen lockfile issue, and speedup through multi stage builds

---

web/components/templates/requests/components/chatComponent/ChatMessage.tsx
web/components/templates/requests/components/chatComponent/single/RenderImageWithPrettyInputKeys.tsx
web/components/templates/requests/components/chatComponent/single/images/ClaudeImage.tsx
web/components/templates/requests/components/chatComponent/single/images/ImageItem.tsx
web/components/templates/requests/components/chatComponent/single/images/ImageModal.tsx
web/components/templates/requests/components/chatComponent/single/renderingUtils.tsx
web/package.json
yarn.lock

This pull request introduces a new, accessible image modal component for viewing images in chat messages and related components. The modal supports zoom, pan, and keyboard navigation, and is now integrated across all image displays in the chat UI for a consistent and improved user experience.
**Major improvements:**
**1. New Image Modal Component**
- Added a reusable `ImageModal` component (`web/components/templates/requests/components/chatComponent/single/images/ImageModal.tsx`) that enables zooming, panning, keyboard navigation (Escape to close), and disables background scrolling when open. The modal uses a portal for rendering and includes controls for zooming, resetting, and centering the image.
**2. Integration of Image Modal Across Components**
- Refactored all image displays in …

feat: open image from drawer in modal

---

docs/getting-started/integration-method/litellm.mdx
packages/llm-mapper/mappers/gemini/chat.ts

- Add warning to LiteLLM callback docs about system instruction limitations
- Add code comments explaining when Gemini system instruction mapping works
- Clarify that proxy integration is needed for full system instruction support

docs: improve system instruction documentation and add clarifying comments

---

web/components/templates/requests/components/chatComponent/ChatMessage.tsx

**Issue:** 
The code was using invalid string concatenation (`uuidv4() + 1`, `uuidv4() + 2`) to generate IDs, which created malformed UUIDs like `"abc123-def4-5678-9012-345678901234"+"1"` resulting in non-unique and invalid identifiers.
**Fix:**
Replaced string concatenation with proper UUID generation (`uuidv4()`) to ensure each message component gets a unique, valid UUID.
**Verification:**
```javascript
const { v4: uuidv4 } = require('uuid');
// Before (buggy):
console.log(`text-${uuidv4() + 1}`); // "text-a5a6701c-d9b5-4cd5-ae98-72ed5ff943d11" (42 chars - INVALID)
// After (fixed):  
console.log(`text-${uuidv4()}`);     // "text-efae76fc-c510-49d7-be53-4456f829c3e5" (41 chars - VALID)
```
**Why:**
- Prevents potential ID collisions in the UI
- Ensures valid UUID format for proper …

fix: resolve UUID collision bug in ChatMessage component

---

.github/workflows/docker-push.yml
docker/push_docker.sh
docker/terraform/github-secrets/.terraform.lock.hcl
docker/terraform/github-secrets/README.md
docker/terraform/github-secrets/main.tf
docker/terraform/github-secrets/outputs.tf
docker/terraform/github-secrets/terraform.tfvars.example
docker/terraform/github-secrets/variables.tf

This pull request introduces support for Docker Build Cloud in the Docker image build and deployment workflows, and enhances the Terraform module to manage the required secrets and variables for both Docker Hub and Docker Build Cloud. The changes improve CI/CD flexibility, make multi-platform builds more robust, and clarify secret management.
**CI/CD Workflow and Build Improvements:**
- Updated `.github/workflows/docker-push.yml` to use repository variables for `DOCKER_USERNAME` and to add a `Set up Docker Build Cloud` step, which utilizes secrets and variables for cloud-based builds.
- Enhanced `docker/push_docker.sh` to detect and use a Docker Build Cloud builder if present, skip local pruning when using cloud builds, and add support for building and pushing a new `helicone-all-in-one` …

feat: also push docker all in one, offload building to docker build cloud

---

bifrost/lib/clients/jawnTypes/private.ts
bifrost/lib/clients/jawnTypes/public.ts
docs/swagger.json
valhalla/jawn/src/controllers/public/prompt2025Controller.ts
valhalla/jawn/src/managers/prompt/PromptManager.ts
valhalla/jawn/src/tsoa-build/private/routes.ts
valhalla/jawn/src/tsoa-build/private/swagger.json
valhalla/jawn/src/tsoa-build/public/routes.ts
valhalla/jawn/src/tsoa-build/public/swagger.json
web/components/templates/playground/components/PlaygroundActions.tsx
web/components/templates/playground/components/PlaygroundHeader.tsx
web/components/templates/playground/components/PlaygroundMessagesPanel.tsx
web/components/templates/playground/components/PromptForm.tsx
web/components/templates/playground/playgroundPage.tsx
web/components/templates/prompts2025/EnvironmentPill.tsx
web/components/templates/prompts2025/PromptDetails.tsx
web/components/templates/prompts2025/PromptVersionCard.tsx
web/components/templates/prompts2025/PromptVersionHistory.tsx
web/components/templates/prompts2025/promptsPage.tsx
web/components/templates/properties/propertiesPage.tsx
web/components/templates/properties/propertyPanel.tsx
web/lib/clients/jawnTypes/private.ts
web/lib/clients/jawnTypes/public.ts
web/services/hooks/prompts.tsx

- Add endpoints to retrieve all environments for an organization
- Update all prompt CRUD endpoints for controlling environment upon creation, update, or manual setting.
- Show environment in the playground if loading a prompt

feat: [ENG-2563] Control prompt environments in UI

---

worker/src/lib/db/PromptStore.ts

On nonexistent environments and version ids, fall back to production version.

feat: [ENG-2717] Fallback to production strategy on prompts

---

bifrost/app/components/Layout.tsx

Remove announcement banner for the AI gateway. Commented it out for the next time we want to use it.

feat: remove announcement banner

---

valhalla/jawn/src/lib/stores/ScoreStore.ts

Added the `cost` field to the returned score object, ensuring that cost information is included in query results.

fix: added missing cost to RequestResponseRMT interface

---

sdk/typescript/helpers/manual_logger/HeliconeManualLogger.ts

**Summary**
- Align the TypeScript HeliconeManualLogger with the Python implementation to support per-call provider routing and accurate endpoint selection.
**Changes**
- Add optional provider to logRequest and resolve endpoint via a private method.
**Impact**
- Brings TS manual logger to functional parity with Python implementation and allows for cost calculation when using HeliconeManualLogger
**Test Proof**
- Most recent 3 requests included 'provider' in the logRequest call and resulted in accurate OpenAI cost calculation
- Previous requests (before the last 3) show the original behavior (no cost calculation even though the model is correctly determined)

feat(sdk-ts): Enable cost calculation in TS HeliconeManualLogger

---

bifrost/lib/clients/jawnTypes/private.ts
bifrost/lib/clients/jawnTypes/public.ts
docs/swagger.json
examples/export/typescript/README.md
examples/export/typescript/index.ts
valhalla/jawn/src/controllers/public/userController.ts
valhalla/jawn/src/index.ts
valhalla/jawn/src/lib/shared/sorts/requests/sorts.ts
valhalla/jawn/src/tsoa-build/private/routes.ts
valhalla/jawn/src/tsoa-build/private/swagger.json
valhalla/jawn/src/tsoa-build/public/routes.ts
valhalla/jawn/src/tsoa-build/public/swagger.json
web/components/templates/gateway/initialColumns.tsx
web/components/templates/requests/initialColumns.tsx
web/components/templates/sessions/sessionId/SessionContent.tsx
web/lib/clients/jawnTypes/private.ts
web/lib/clients/jawnTypes/public.ts
web/lib/sessions/sessionTypes.ts
web/lib/sessions/sessionsFromHeliconeTequests.ts
web/services/hooks/requests.tsx
web/services/lib/sorts/requests/sorts.ts

Sorting by cost wouldn't work since cost_usd no longer exists as a synthetic column anymore. Now cost is a real column in `request_response_rmt` and can be filtered/sorted as such.
Replaces `cost_usd` with `cost`.

fix: [ENG-2760] remove cost_usd naming, fix cost sorting

---

worker/src/lib/util/aiGateway.ts

fixes bug where if you specified environment but not prompt id it would fail at the provider layer rather than the gateway layer - since environment passes through in the request body.

fix: [ENG-2754] check all prompt args in gateway

---

valhalla/jawn/src/lib/db/ClickhouseWrapper.ts

This pull request increases the maximum number of rows that can be read in a Clickhouse query from 10 million to 100 million. This change allows for larger queries to be executed, which may be necessary for processing bigger datasets.

fix: hql clickhouse query count

---

valhalla/jawn/src/lib/db/ClickhouseWrapper.ts
valhalla/jawn/src/lib/db/test/TestClickhouseWrapper.ts

**Type consistency improvements:**
All query methods in both `ClickhouseClientWrapper` and `TestClickhouseClientWrapper` now use the generic type parameter `T` and consistently return `Promise<Result<T[], string>>` instead of sometimes returning single objects or using `RowType` as the generic. [[1]](diffhunk://#diff-6285f1308e9e3889f3c76edc6c2fc36d2bb3de426418c2ce8c5c44986933a2f5L93-R101) [[2]](diffhunk://#diff-50c29d826b97a1f8eb58ef5de04d29de1844cd2f7ca1584f77bbfd5bb7bfdbdeL60-R63) [[3]](diffhunk://#diff-50c29d826b97a1f8eb58ef5de04d29de1844cd2f7ca1584f77bbfd5bb7bfdbdeL84-R87) [[4]](diffhunk://#diff-50c29d826b97a1f8eb58ef5de04d29de1844cd2f7ca1584f77bbfd5bb7bfdbdeL108-R116)

fix: replace RowType with T type

---

web/components/shared/LivePill.tsx
web/components/shared/themed/themedHeader.tsx
web/components/shared/themed/themedTimeFilter.tsx
web/components/shared/themed/themedTimeFilterShadCN.tsx
web/components/templates/dashboard/dashboardPage.tsx
web/components/templates/requests/RequestsPage.tsx

Indicate more strongly in UI that the Live mode is on. Primarily, by making the little widdle spinning logo go fast
and by making time filter show 'Now'

feat: [ENG-2776] Clear live time filter visuals

---

sdk/typescript/helpers/package-lock.json
sdk/typescript/helpers/package.json
sdk/typescript/helpers/tsconfig.json
sdk/typescript/helpers/tsup.config.ts

Helpers SDK build was not bundling the @helicone-package types correctly - so functionality was preserved (by tsup bundling) but `HeliconePromptManager` shows as `any`.

fix: [ENG-2849] Fix improper bundling of helicone-package in helpers sdk

---

docs/getting-started/integration-method/vercelai.mdx

Backticks were missing causing the docs to not render the Gemini part.

Fix Vercel AI SDK docs

---

packages/filters/toFilterNode.ts
web/components/templates/dashboard/dashboardPage.tsx
web/components/templates/dashboard/useDashboardPage.tsx
web/components/templates/properties/propertyPanel.tsx
web/components/templates/requests/useRequestsPageV2.tsx
web/pages/sessions/[name]/[session_id].tsx
web/services/hooks/sessions.tsx
web/services/hooks/users.tsx

This pull request refactors the import paths for the `toFilterNode` utility and its dependencies, consolidating them under the `@helicone-package/filters` package. This change improves code organization and modularity by ensuring all references to `toFilterNode` use the shared package location, rather than local paths. Additionally, the internal imports within `toFilterNode` itself are updated to use relative paths, reflecting its new location.
**Refactoring imports to use shared package paths:**
* Updated all occurrences of `import { toFilterNode } from "@/filterAST/toFilterNode"` to `import { toFilterNode } from "@helicone-package/filters/toFilterNode"` across multiple files, including `dashboardPage.tsx`, `useDashboardPage.tsx`, `propertyPanel.tsx`, `useRequestsPageV2.tsx`, …

refactor: move toFilterNode to packages sdk

---

web/components/templates/agent/HeliconeAgentContext.tsx
web/components/templates/agent/MessageRenderer.tsx
web/components/templates/agent/agentChat.tsx
web/components/templates/quickstart/HelixIntegrationDialog.tsx
web/components/templates/quickstart/integrationGuide.tsx
web/components/templates/quickstart/quickstartPage.tsx
web/data/providers.ts
web/lib/agent/tools.ts

Integrates Helix into the quickstart flow
- created `HeliconeIntegrationDialog` that shows a 3 step process where users provide the language+sdk of choice
- adds button to open dialog in the helix chat
- open helix chat by default in the `/quickstart` page

feat: [ENG-2692] Helix in Quickstart

---

web/components/templates/hql/QueryResult.tsx

This pull request makes a small change to the `QueryResult` component in `web/components/templates/hql/QueryResult.tsx`. The loading animation that was previously shown while a query was running has been removed, so the results table now renders immediately without displaying a loading indicator. [[1]](diffhunk://#diff-f685bd6421ee729c98e7379886ba3f57b6bc70fb6efecd46cbfed6ea5e712f65L80-L84) [[2]](diffhunk://#diff-f685bd6421ee729c98e7379886ba3f57b6bc70fb6efecd46cbfed6ea5e712f65L115)

misc: remove loading bar for hql

---

docs/getting-started/self-host/docker.mdx

The latest version is broken, so updated the docs to use the stable version.

docs: Update all in one to the version which was working

---

web/components/shared/themed/table/columns/draggableColumnHeader.tsx

This pull request makes a minor UI improvement to the dropdown menu in the `DraggableColumnHeader` component. The change ensures that the menu appears above other elements by increasing its stacking context.
* UI enhancement: Added `z-50` to the dropdown menu's class in `draggableColumnHeader.tsx` to fix layering issues and ensure the menu displays above other content.

fix: sorting UI

---

valhalla/jawn/src/lib/stores/AlertStore.ts

Instead of selecting all columns with `SELECT *`, the queries now explicitly specify the required columns for both the `alert` and `alert_history` tables.

refactor: Expand * query for AlertStore

---

worker/test/alerts/alertManager.spec.ts
worker/test/alerts/alertStore.spec.ts
worker/test/alerts/slackAlertManager.spec.ts
worker/test/alerts/vitest.config.mts
worker/vitest.config.mts

* Added `AlertManager` unit tests to verify alert triggering, resolution logic, and integration with mocked dependencies.
* Added `AlertStore` unit tests to validate alert retrieval, status updates, history insertion, and Clickhouse query mapping.
* Added `SlackAlertManager` unit tests to check Slack message sending and error handling for missing webhook configuration.
**Test configuration improvements:**
* Created a dedicated Vitest config file for alerts tests in `worker/test/alerts/vitest.config.mts`, including module aliasing for easier imports.
* Registered the alerts test configuration in the main Vitest config `worker/vitest.config.mts` to ensure alerts tests are run with the overall test suite.

tests(worker): alerts

---

bifrost/app/pi/first_page/useTestApiKey.tsx
docs/swagger.json
examples/export/typescript/index.ts
packages/__tests__/filters/toFilterNode.test.js
packages/filters/filterDefs.ts
packages/filters/toFilterNode.ts
valhalla/jawn/src/controllers/public/promptController.ts
valhalla/jawn/src/controllers/public/propertyController.ts
valhalla/jawn/src/controllers/public/requestController.ts
valhalla/jawn/src/controllers/public/sessionController.ts
valhalla/jawn/src/managers/eval/EvalManager.ts
valhalla/jawn/src/tsoa-build/private/swagger.json
valhalla/jawn/src/tsoa-build/public/swagger.json
web/components/layout/onboardingContext.tsx
web/components/templates/dashboard/dashboardPage.tsx
web/components/templates/dashboard/useDashboardPage.tsx
web/components/templates/evals/CreateNewEvaluator/components/TestEvaluator.new.tsx
web/components/templates/evals/CreateNewEvaluator/components/TestEvaluator.tsx
web/components/templates/evals/details/TestDrawer.tsx
web/components/templates/models/modelPage.tsx
web/components/templates/requests/useRequestsPageV2.tsx
web/lib/api/cache/stats.ts
web/lib/api/properties/properties.ts
web/pages/api/has_converted.ts
web/pages/api/user/checkOnboarded.ts
web/services/hooks/country.tsx
web/services/hooks/models.tsx
web/services/hooks/prompts/prompts.tsx
web/services/hooks/sessions.tsx
web/services/hooks/users.tsx

This pull request standardizes the representation of an "all" filter across the codebase, replacing the string `"all"` with an empty filter object `{}` (typed as `FilterLeaf` where appropriate). This change affects backend controllers, frontend components, filter conversion logic, and documentation, ensuring consistency in how the absence of filter criteria is handled and passed throughout the system.
**Filter Representation Standardization**
* Updated all usages of `"all"` as a filter value to `{}` in backend controllers (`PromptController`, `PropertyController`, `RequestController`, `SessionController`, `EvalManager`) to ensure consistent filter handling in API requests. [[1]](diffhunk://#diff-8efde93d9cdbb350648e9b56a756d4a3be550cbe354704c47c7af977263b3ae0L161-R161) …

refactor: Use empty JSON instead of "all" string for filter consistency

---

valhalla/jawn/src/managers/creditsManager.ts
worker/src/api/lib/apiClient.ts
worker/src/api/lib/internalResponse.ts
worker/src/routers/api/apiRouter.ts

the manual access key is not a proper helicone key, so we are throwing on auth header validation. Even tho we dont validate it. To fix this we can remove the APIClient completely, since we are just using the underlying response helper and pull that out into it's own class

update to use internal responses over apiclient

---

web/filterAST/FilterASTButton.tsx
web/filterAST/FilterASTEditor.tsx
web/filterAST/components/SavedFiltersDropdown.tsx

no ticket
remove the saved filters button from the filters popover and put them side by side. 1 less click needed
this change was requested by a customer:
[customer's slack message](https://helicone.slack.com/archives/C08TU3RV8CF/p1748932194174729)
| **Before**   |  **After**  |
|-------------|------------|
|<img width="428" height="106" alt="Screenshot 2025-09-06 at 11 37 18 AM" src="https://github.com/user-attachments/assets/9fe174c5-43c2-429c-8055-a1ebba3c8dcb" /><img width="575" height="64" alt="Screenshot 2025-09-06 at 11 38 51 AM" src="https://github.com/user-attachments/assets/1ddf3e29-ce40-49f5-8991-16453c8d7fb9" />|<img width="542" height="108" alt="Screenshot 2025-09-06 at 11 29 34 AM" src="https://github.com/user-attachments/assets/f93498af-327d-4cde-8fb5-d8b229b69f47" /><img …

separate saved filters button from filters dropdown

---

bifrost/lib/clients/jawnTypes/public.ts
docs/features/hql.mdx
docs/swagger.json
valhalla/jawn/src/controllers/public/heliconeSqlController.ts
valhalla/jawn/src/tsoa-build/private/swagger.json
valhalla/jawn/src/tsoa-build/public/routes.ts
valhalla/jawn/src/tsoa-build/public/swagger.json
valhalla/jawn/tsoa-private.json
valhalla/jawn/tsoa-public.json
web/components/templates/hql/constants.ts
web/lib/clients/jawnTypes/private.ts
web/lib/clients/jawnTypes/public.ts

Added API documentation to swagger for the HQL API.
Also bundled into this PR:
API Restructuring: The updateSavedQuery endpoint is refactored from PUT /saved-query to PUT /saved-query/{queryId} to follow RESTful conventions where resource IDs should be in the URL path rather than request body.

docs: hql api

---

valhalla/jawn/src/controllers/public/heliconeSqlController.ts
valhalla/jawn/src/lib/decorators/tracing.ts
valhalla/jawn/src/managers/HeliconeSqlManager.ts

This pull request introduces comprehensive tracing for HQL. It adds new tracing decorators, applies them to all public endpoints and core logic, and enriches traces with detailed tags for both successful and error cases.
This will give an idea of how customers use HQL.

feat: datadog traces for hql

---

docs/features/advanced-usage/caching.mdx
docs/gateway/concepts/prompt-caching.mdx

Since we've added provider caching with Anthropic via cache control breakpoints to AI Gateway, update the docs accordingly:

docs: [ENG-3130] caching docs to explain provider caching with anthropic

---

worker/src/lib/HeliconeProxyRequest/ErrorForwarder.ts
worker/src/lib/ai-gateway/SimpleAIGateway.ts
worker/src/lib/ai-gateway/types.ts

for AI Gateway, make everything use the `AttemptError` type. update the gateway so that, if no providers are found, we still will log this to helicone.
+ other misc fixes

feat: [ENG-3174] cleaner error handling, and log when providers not found

---

worker/RequestBodyBufferContainer/src/app.ts
worker/src/RequestBodyBuffer/IRequestBodyBuffer.ts
worker/src/RequestBodyBuffer/RequestBodyBuffer_InMemory.ts
worker/src/RequestBodyBuffer/RequestBodyBuffer_Remote.ts
worker/src/lib/RequestWrapper.ts
worker/src/lib/ai-gateway/SimpleAIGateway.ts
worker/src/lib/models/HeliconeProxyRequest.ts
worker/src/lib/util/cache/cacheFunctions.ts
worker/test/ai-gateway/test-framework.ts
worker/test/cache/cacheFunctions.spec.ts
worker/test/cache/simpleCache.spec.ts

Fix problem where:
- We were not updating stream usage or applying body key overrides to the body before we sent to the provider
Solution:
- Add interface for the RequestBodyBuffers to let you apply body key overrides (allowing us to update the body without loading the whole thing into memory, e.g with modifying the stream usage inclusion parameter)
- For InMemory, just apply override locally
- For Remote, send req to new container endpoint which applies it locally
Then in `HeliconeProxyRequest`, we try to safelyGetBody. 
- If we need to format it to prompts (legacy prompts system) then we can't really avoid loading it into memory so we just bite the bullet and load it. (TODO: fix) If this is the case, then we just cry, load into memory and return.
- Otherwise, we use the body buffer …

fix: [ENG-3224] safely apply overrides and retrieve on buffer
